pencil2d/pencil

- app/mainwindow2.cpp
- core_lib/interface/editor.cpp
- core_lib/interface/editor.h
- core_lib/interface/preferences.cpp
- core_lib/interface/preferences.h
- core_lib/interface/scribblearea.cpp
- core_lib/util/pencildef.h
Implement this request: https://github.com/pencil2d/pencil/issues/17 . This first step adds these options to a setting menu. A better GUI interface, as discussed in the request, should be added later.
Adds options in Edit > Preferences > Tools so that the user may define how many previous and next frames are shown when previous and/or next onion skinning is toggled on. The user may also define a maximum opacity value and a minimum opacity value, which will be gradated between all of the frames shown. Replaces the previous options here which allowed the user to define the opacity values for the next or previous 3 onion frames explicitly; these settings were broken and did not work.
> Add options to onion skinning so user may define the number of frames shown

- resources/translations/translations.pro
If the translations lib is not defined as a static library, build fails because the compiler is looking for a main file that doesn't exist.
> Make translations a static library

- app/mainwindow2.cpp
- app/mainwindow2.h
- core_lib/interface/scribblearea.cpp
- core_lib/interface/spinslider.cpp
- core_lib/interface/tooloptiondockwidget.cpp
- core_lib/interface/tooloptiondockwidget.h
- core_lib/managers/toolmanager.cpp
- core_lib/managers/toolmanager.h
- core_lib/tool/basetool.cpp
- core_lib/tool/basetool.h
- core_lib/tool/brushtool.cpp
- core_lib/tool/brushtool.h
- core_lib/tool/erasertool.cpp
- core_lib/tool/erasertool.h
- core_lib/tool/penciltool.cpp
- core_lib/tool/penciltool.h
- core_lib/tool/pentool.cpp
- core_lib/tool/pentool.h
- core_lib/tool/polylinetool.cpp
- core_lib/tool/polylinetool.h
- core_lib/tool/smudgetool.cpp
- core_lib/tool/smudgetool.h
When working on a tablet, erasing with the back of the stylus worked but the current selected tool wasn't restored when using the point of the stylus again. It is fixed with this commit.
I also fixed the fact that when selecting a new tool, its settings where not updated correctly.
Finally, I made the pencil tool feel more like a real pencil.
Updates : I also fixed most of the tools options and made their controls appear or disappear depending on the option's availability for the selected tool. The non working options never appear.
Most of the bitmap brush engine is fixed in this version and is very usable! Only the polyline tool is not working completely as expected.
Thanks!
> Fixes on bitmap brush engine.

- app/colorbox.cpp
- app/mainwindow2.cpp
- core_lib/canvasrenderer.cpp
- core_lib/canvasrenderer.h
- core_lib/graphics/bitmap/bitmapimage.cpp
- core_lib/graphics/bitmap/bitmapimage.h
- core_lib/graphics/vector/beziercurve.cpp
- core_lib/graphics/vector/vectorimage.cpp
- core_lib/interface/backgroundwidget.cpp
- core_lib/interface/backgroundwidget.h
- core_lib/interface/editor.cpp
- core_lib/interface/scribblearea.cpp
- core_lib/interface/scribblearea.h
- core_lib/managers/viewmanager.cpp
- core_lib/structure/object.cpp
- core_lib/structure/object.h
- core_lib/structure/objectsaveloader.cpp
- core_lib/tool/brushtool.cpp
- core_lib/tool/movetool.cpp
- core_lib/tool/movetool.h
- core_lib/tool/penciltool.cpp
- core_lib/tool/pentool.cpp
- core_lib/tool/selecttool.cpp
- core_lib/tool/selecttool.h
- core_lib/tool/stroketool.cpp
- core_lib/tool/stroketool.h
Here is my weekly contribution. The entire app starts to be pretty usable, I am quite happy with the result.
When you select an area with the select tool, you can transform your selection (move, scale, rotate) and cancel your transformation by clicking escape. The transformation is only applied on deselect.
For some reason, the move tool doesn't work well on the vector layer when a key is pressed, which makes rotation impossible on a vector selection. I will fix that for the next pull request.
Duplicating a frame now handles the entire frame and not just the screen area. It is also the case when you do select all. The entire frame is selected even if it is larger that the screen area.
Enjoy! :)
> Weekly updates

- core_lib/tool/stroketool.cpp
Fixes #402
In the case where the current tool does not handle the event, the event should not be terminated
> Return proper values for stroke key events

- core_lib/interface/timelinecells.cpp
- core_lib/managers/toolmanager.cpp
- core_lib/tool/basetool.cpp
- core_lib/tool/basetool.h
- core_lib/tool/movetool.cpp
- core_lib/tool/movetool.h
Apply changes of the move when switching to a new tool
This should fix the bug in #385
> Fix select, move, brush bug

- core_lib/interface/scribblearea.cpp
- core_lib/interface/tooloptiondockwidget.cpp
- core_lib/tool/basetool.cpp
- core_lib/tool/basetool.h
Fixes #308 
Shift is used for size
Ctrl is used for feather
Min and max settings for both were changed to 1 to 200 for size and 2 to 64 for feather (both integers now)
> Size shortcut 308

- core_lib/interface/spinslider.cpp
- core_lib/interface/spinslider.h
- core_lib/interface/tooloptiondockwidget.cpp
- core_lib/interface/tooloptiondockwidget.h
This should make it much easier to select precise values.
~~ideally i want to remove the smaller brush number and update the spinBox simultaneously instead. Right now it's only updating when you let go of the slider and of course when you insert a value or use the arrows or use the shortcuts to change size.~~
fixed it! now, as there is no need for the brush number to be shown twice anymore, i have removed the smaller text showing its value and instead made it so the SpinBox updates simultaneously with the slider.
the new UI looks like so:
(http://i.imgbox.com/4mDuOTZv.png)
> added option to type brush and feather size

- core_lib/canvasrenderer.cpp
Fixes bug : https://github.com/pencil2d/pencil/issues/386
The current selected layer was always rendered on top of the others. This broke the "paint on a different layer" feature because as soon as we were working on the colour layer for adjustments, we were overlapping the strokes.
> Fixed layers rendering order

- app/colorbox.cpp
- app/colorinspector.cpp
- app/colorwheel.cpp
- app/colorwheel.h
- app/ui/colorinspector.ui
Color wheel and color square has been centred to the widget and is resizable to a certain extend. 
Fixed the region focus when resizing the window, now it is possible to resize and still
use the colorwheel hue indicator.
m_wheelWidth has been renamed to m_wheelThickness. 
color label has been positioned below inspector instead of next to.
constrained the widget to not be able to resize to fill the whole application window.
#430
> Centered color wheel and square, set contrains for widget #430

- app/displayoptionwidget.cpp
- app/displayoptionwidget.h
- app/preferencesdialog.cpp
- app/preferencesdialog.h
- app/ui/displayoption.ui
- core_lib/canvasrenderer.cpp
- core_lib/canvasrenderer.h
- core_lib/interface/scribblearea.cpp
- core_lib/interface/scribblearea.h
- core_lib/interface/tooloptiondockwidget.cpp
- core_lib/interface/tooloptiondockwidget.h
- core_lib/managers/preferencemanager.cpp
- core_lib/managers/preferencemanager.h
- core_lib/managers/toolmanager.cpp
- core_lib/managers/toolmanager.h
- core_lib/tool/basetool.cpp
- core_lib/tool/basetool.h
- core_lib/tool/brushtool.cpp
- core_lib/tool/brushtool.h
- core_lib/tool/eyedroppertool.cpp
- core_lib/tool/handtool.cpp
- core_lib/tool/movetool.cpp
- core_lib/util/pencildef.h
This fork adds the ability to customize grid size in preferences, to make a single point brush stroke, to see the current zoom level, and to disable brush feathering for a "pixel brush" effect. I got the OK from Matt so I figured I'd go ahead and submit a pull request now.
> Single-point brush strokes, grid customization, zoom info, optional pixel brush

- core_lib/interface/scribblearea.cpp
- core_lib/interface/scribblearea.h
- core_lib/managers/preferencemanager.cpp
- core_lib/managers/preferencemanager.h
- core_lib/tool/basetool.cpp
- core_lib/util/pencildef.h
Added a toggle in the General -> Editing section of the Preferences menu to turn on and off Quick feather/width resizing using CTRL+SHIFT.
> #468 Added ctrl/shift quick sizing toggle

- core_lib/interface/scribblearea.cpp
- core_lib/structure/layer.cpp
- Fixed eraser behavior when using it through the SHIFT + CTRL keyboard shortcut.
- Fixed crash when moving the first frame in the timeline (re-create a new first frame)
> Bug fixing

- core_lib/managers/viewmanager.cpp
- core_lib/managers/viewmanager.h
You can currently zoom out to infinity or float overflow which is probably an issue.  All this does is clamp the zoom to 1-10000%.
> Clamped view scale (zoom) to [1%-10000%]

- app/mainwindow2.cpp
- core_lib/soundplayer.cpp
Quick fix for image sequences export.
It is not necessary to select the camera when there is only one. If there are several cameras, the last created or selected one will be used for the export.
> Fixed Export as Image Sequence without selecting the camera.

- 3rdlib/quazip/quazip.pro
quazip headers are not needed by pencil2d, so do not bother to install them at all
> do not install quazip headers

- app/colorinspector.cpp
- app/ui/colorinspector.ui
This adds a checkerboard background underneath the color preview box in the color inspector to make it easy to see when a color is transparent. Here's what the end result looks like:
> Added transparency checkerboard to color inspector preview box

- core_lib/interface/spinslider.cpp
- core_lib/interface/spinslider.h
- core_lib/interface/tooloptiondockwidget.cpp
Improved the following things in the spinslider class:
- Fixed bug where moving the slider by clicking without dragging failed to emit valueChanged
- Fixed bug where logarithmic growth rates weren't taking effect
- Added support for exponential growth rates (and setting the exponent to fine-tune the result)
I also changed the brush size spinslider to use the new exponential growth rate because logarithmic felt a bit to sharp (with log it's about 20 at the halfway out of 200, whereas with exponential with exponent 2 it's 50 at the halfway).
> SpinSlider improvements

- app/main.cpp
- app/mainwindow2.cpp
- core_lib/interface/editor.cpp
- core_lib/interface/editor.h
This is a mixture of bug fixes and enhancements for the command line interface. I have made a lot of changes, but they _should_ be backwards-compatible with the latest stable release.
A list significant changes:
- Fixed camera layer size being ignored
- Prevented GUI from opening when rendering from command line
- Added support for exporting multiple sequences
- Created `-o` alias for `--export-sequence`
- Added `-h`/`--help` and `-v`/`--version` flags
- Added optional arguments for rendering: `--width`, `--height`, and `--transparency`
> CLI Overhaul

- app/mainwindow2.cpp
- app/mainwindow2.h
- core_lib/interface/editor.cpp
- core_lib/interface/editor.h
This fixes the bug where users would not be warned when closing a modified document. Additionally it removes the modification marker (*) from the title if changes are undone/redone to the save point (making it effectively unmodified).
Fixes #387
See also #282 and #527
> Improve unsaved changes behavior

- core_lib/graphics/vector/vectorimage.cpp
- core_lib/interface/editor.cpp
Several object allocation without calling deleting it after.
Due object are used in the same scope, heap allocation is not needed, intead using stack allocation for better resource management (auto delete and file close).
> Fix memory leaks at importing images

- core_lib/interface/scribblearea.cpp
Here's a tiny baby commit.
This modifies the program so spin boxes in the tool options widget don't lose focus when typing values in with the keyboard. 
ex. You can now input 34 as the brush size without needing to click back into the spin box to type the second digit.
> Spinbox focus loss bug fix

- app/filedialogex.cpp
- app/mainwindow2.cpp
- core_lib/util/pencildef.h
Some very minor changes to the file type filters for importing and exporting. Changes:
- Modified formatting of export option labels to match import option formatting
- Added support for importing TIFF sequences
- Set the default import option to all image types. This is especially important for Mac, since the file type option is hidden by default, potentially leading people to think that only PNGs can be imported.
> Improve import import and export dialogs

- core_lib/movieexporter.cpp
This patch is working on my linux system without any problem.
You must/may add ffmpeg as dependency or as a recommended package for Pencil2D's .deb and .rpm packages.
ffmpeg is a standalone project/package so if you install Pencil2D on a Linux system (normally with a package manager) then you can not use it in a plugin-like directory structure (as you do it on windows or apple systems).
The windows/apple way may work if Pencil2D is installed in user's home directory (/home/auser/Pencil2D) then ffmpeg can be placed in a subdirectory (/home/auser/Pencil2D/plugins), but this way each user on the system must install a new copy of Pencil2D and ffmpeg.
In my oppinion the best solution on all systems would be to search ffmpeg on the PATH and then (if not found) ask the user to select the ffmpeg …
> Working ffmpeg call on Linux systems (patch)

- app/mainwindow2.cpp
- core_lib/interface/tooloptiondockwidget.cpp
- core_lib/interface/tooloptiondockwidget.h
- core_lib/managers/toolmanager.cpp
- core_lib/managers/toolmanager.h
- core_lib/tool/basetool.cpp
- core_lib/tool/basetool.h
- core_lib/tool/penciltool.cpp
- core_lib/tool/pentool.cpp
- core_lib/util/pencildef.h
A fix for #244. I added a checkbox called "Merge" to the Tool Options panel. When it is checked, new vector lines are merged with existing ones. If unchecked, this merging does not happen.
By default it is un-checked.
This checkbox is only visible when both 1) a vector layer is selected and 2) either the pencil or pen tool are selected. (The pencil and pen tool are the only ones which can do vector merging).
Below is a screenshot:
Below is a video demo (zipped):
[Bug_244_Fix_Demo.zip](https://github.com/pencil2d/pencil/files/707642/Bug_244_Fix_Demo.zip)
What do you think?
> Added yes-no option for vector merge

- core_lib/interface/scribblearea.cpp
- core_lib/interface/scribblearea.h
- core_lib/tool/polylinetool.cpp
Fix for #565. Pressing the ESC key now clears the in-progress polyline.
> Fix for #565. ESC key now clears polyline.

- core_lib/interface/scribblearea.cpp
- core_lib/tool/penciltool.cpp
This should fix #596 and maybe also solve #595
* Removed division from opacity in ScribbleArea
* feather has also been set to 1 in PencilTool, as it seemed to have no influence on the look, except the cursor radius.
* The opacity pressure has been modified to be consistent with how it works in brushTool. I see no reason why the Pencil should act differently.
Is there a a reason as to why the opacity was being divided before drawing the stroke?
> Removed division from opacity and set feather to 1

- core_lib/managers/playbackmanager.cpp
- core_lib/managers/playbackmanager.h
- core_lib/soundplayer.cpp
- core_lib/soundplayer.h
- core_lib/structure/layer.cpp
- core_lib/structure/layer.h
- core_lib/structure/soundclip.cpp
- core_lib/structure/soundclip.h
Fix for #547. You can now play a sound from any frame in its duration, not just its starting frame.
You can also delete and move the sound from any frame.
**Code Changes:**
- Added "mCheckForSoundsHalfway" flag to PlaybackManager. Set to true when starting playback - to check whether to play any sound from part-way through.
- Added "getKeyFrameWhichCovers(pos)" to Layer. This returns the keyframe which covers pos. E.g. a sound clip starting at frame 1 and ending at frame 6 covers frames 1, 2, 3, 4, 5, 6. 
- Updated Layer methods "isFrameSelected(pos)" and "setFrameSelected(pos)" to use "getKeyFrameWhichCovers". I could possibly move this logic change to the LayerSound class and keep Layer as is.
- Added "playFromPosition()" to SoundClip to play sound from part-way through.
> Fix for #547. Can play and delete sound from any frame in its length.

- app/colorpalettewidget.cpp
- app/colorpalettewidget.h
- app/ui/colorpalette.ui
- Palette widget and items take up much less space. We don't want to waste all that space on nothing.
- Added checkerboard background so all colors can be seen. 
- Added a palette preference button 
- Switch between list mode and a NEW tile mod.
- Change swatch size (small, medium and large)
Other things that can't be seen in the gif:
Creating a new color in tile mode will not ask about name, the new color will appear unnamed if switched to list mode though. For those who don't care about naming their colors, this should be great.
Colors should be draggable in both list and tile mode.
Double click to add color from color picker or color wheel.
> Palette UI changes

- core_lib/interface/scribblearea.cpp
Some tablets are not recognized because TabletEvent only expects a pointerType. This PR adds a NoDevice condition for tablets that are not recognized as a Stylus, likewise PointerType: Cursor is not fail proof either, my tablet was recognized as a Cursor even if it was a pen.
My non Wacom tablet works now, so this should definitely increase compatibility for those who use other tablet brands.
> Some tablets are not recognized

- app/preferencesdialog.cpp
- app/preferencesdialog.h
Grid page removed, moved to general page. In addition to that, it is
also now possible to enable/disable grid from preferences.
General page is resizable now, if the content overflow the height, a
scrollbar will appear.
Renamed "Rendering" to "Canvas", ~~this has to be changed thorough the project at some point because canvas AA is not the same as brush AA. Brush should have its own independent AA setting, preferably in the brush panel.~~  implemented in #611.
> Grid page removed, added to general page

- core_lib/interface/scribblearea.cpp
- core_lib/interface/scribblearea.h
- core_lib/interface/tooloptiondockwidget.cpp
- core_lib/interface/tooloptiondockwidget.h
- core_lib/managers/toolmanager.cpp
- core_lib/managers/toolmanager.h
- core_lib/tool/basetool.cpp
- core_lib/tool/basetool.h
- core_lib/tool/brushtool.cpp
- core_lib/tool/penciltool.cpp
- core_lib/tool/penciltool.h
- core_lib/tool/pentool.cpp
- core_lib/tool/pentool.h
- core_lib/tool/polylinetool.cpp
- core_lib/tool/polylinetool.h
- core_lib/tool/strokemanager.cpp
- core_lib/util/pencildef.h
- Opacity strokes being drawn on top of each other instead of being continuous
for Pen and Brush.
- Separated painting/brush Anti-Aliasing from the Preferences
Anti-aliasing setting.
- Set fixed step size for pen. In the future I want to control this via a slider, but it should be hidden in a popup window, so for now it's fixed instead of relying on the feather value.
- Feather from Pen
- Checkbox to enable AA for brushes, this is used for Pen only. AA is
redundant for Brush and Pencil when feather is enabled and is otherwise
enabled.
- Consistent dap ability across Pencil, Brush and Pen. Before this was only possible with brush.
- Dotted Cursor for Pen tool.
> Brush/Tools changes, AA Brush setting and more..

- app/mainwindow2.cpp
- core_lib/structure/object.cpp
Fix fox #612. You can now export images and image sequences even when there is no camera layer. In that case the export dialog will have a default size setting of 640 by 480 pixels.
> You can now export images without a camera layer

- app/mainwindow2.cpp
- core_lib/structure/object.cpp
Added a progress dialog for exporting image sequences. Shows how far through the export is, and you can stop the export by clicking "Abort".  Below is a video demo:
[Progressbar Demo.zip](https://github.com/pencil2d/pencil/files/805477/Progressbar.Demo.zip)
The reason for this is:
1. When exporting image sequences, I couldn't tell how far Pencil was through, so I just had to wait till it became responsive again. This sometimes took a few minutes for very long animations.
2. There was no way to cancel the export, so I would either have to kill the application or just wait till the export eventually finished.
> Added progress dialog (with cancel option) for exporting image sequences

- util/nightly-build-upload.py
As per discussion in #582. This script will allow automatic nightly builds to be uploaded to GDrive via CI. It requires Python 3 and the [google-api-python-client](https://pypi.python.org/pypi/google-api-python-client) Python package. (I originally tried to do it with simpler means and no additional dependencies but the amount of complexity in Google’s authorization API is honestly quite ridiculous, so I gave up.)
Obtaining the right API credentials and setting everything up is a pretty tricky too, but I’ll make a detailed guide on that tomorrow.
> Add script for uploading nightly builds to Google Drive

- core_lib/interface/scribblearea.cpp
- core_lib/interface/scribblearea.h
- core_lib/interface/spinslider.cpp
- core_lib/interface/tooloptiondockwidget.cpp
- core_lib/interface/tooloptiondockwidget.h
- core_lib/managers/toolmanager.cpp
- core_lib/managers/toolmanager.h
- core_lib/tool/basetool.cpp
- core_lib/tool/basetool.h
- core_lib/tool/brushtool.cpp
- core_lib/tool/brushtool.h
- core_lib/tool/buckettool.cpp
- core_lib/tool/erasertool.cpp
- core_lib/tool/erasertool.h
- core_lib/tool/eyedroppertool.cpp
- core_lib/tool/handtool.cpp
- core_lib/tool/movetool.cpp
- core_lib/tool/penciltool.cpp
- core_lib/tool/penciltool.h
- core_lib/tool/pentool.cpp
- core_lib/tool/pentool.h
- core_lib/tool/polylinetool.cpp
- core_lib/tool/polylinetool.h
- core_lib/tool/selecttool.cpp
- core_lib/tool/smudgetool.cpp
- core_lib/tool/strokemanager.cpp
- core_lib/tool/strokemanager.h
- core_lib/tool/stroketool.cpp
- core_lib/util/pencildef.h
- interpolation levels:
Non -- Simple -- Strong
Interpolatino can be applied to:
Pen, Brush, Pencil and Eraser.
The mean interpolation operation is ported from Krita. 
The smooth operation that was removed in my last PR has been added again too.
------ 
- Invisibility checkbox for brush
- All drawing tools have gone through code refactoring.
- Spinslider maximum width changed
- Temporary raster preview of vector drawing is much closer to the final output now.
Prior to this, the line would become thicker after the vector path had been generated.
At some point I want to make a list widget class for small items with icons that can be used for various settings.
For example the interpolation levels should look likes squares that are filled with a color, brighter color means lighter …
> Interpolation levels and refactoring

- pencil.pro
a379816fefaa5bb9ecd7e313b701d19bb2d4e3e2 added pencil.ts to TRANSLATIONS, but doing so it broke the syntax of the list.
> Fix syntax

- .travis.yml
I've tested everything aside from the upload process to google drive, since the private key is not set up for my account. if @chchwy has made the preparations mentioned in #617, my assumption is that it'll work when the PR has been merged.
The changes to the Travis file should in the end upload two files to google drive, one for linux and another for mac. The zip files are named like this: pencil2d-os-date where os is linux or mac and date is year-month-day
As i've previously said, Travis-CI doesn't support Windows yet, so at some point i'll see if I can get it setup on Appveyor too but that's a task for another day.
> make travis ready for google drive integration

- .travis.yml
Alright this should fix some terrible typos and move the builds into the their respective folders.
> Typos and move builds into folders

- .travis.yml
In the recent CI build I noticed that right now the Travis script still tries to upload the ZIP file on Linux even though we switched to tar.gz.
> Fix Linux upload

- app/mainwindow2.cpp
- app/mainwindow2.h
Instead of manually prepending the asterisk to the window title to indicate file changes, this lets QT handle it. On Window and Linux I don't think there will be any noticeable difference from this change, but on Mac, the close button will change when the current file has unsaved changes. I have also added a file icon to the window title (again probably mac only), which will be greyed out slightly when there are unsaved changes, as is typical of Mac applications.
> Refactor title save indicator and add file icon to main window title

- app/ui/displayoption.ui
- app/ui/mainwindow2.ui
This removes custom styling of the menu bar and the display option buttons, which makes Pencil play along much more nicely with system themes (i.e. #550). Before:
After:
> Remove custom styling

- core_lib/movieexporter.cpp
I just tested movie export on mac in the newest nightly build and noticed that it didn't work, because the ffmpeg path was wrong. i'm curious as to how it knew where to find the executable in the builds you provided @chchwy because the source code didn't look for a plugins folder inside MacOs/, so it shouldn't work. 
I've added more specific debug too.
> fix ffmpeg path on MacOS

- core_lib/tool/handtool.cpp
- core_lib/tool/handtool.h
Just a couple of improvements for the hand tool. It now uses the native Qt::OpenHandCursor, and changes to Qt::ClosedHandCursor while dragging. Rotation behavior with alt click has been basically rewritten. I honestly am not even sure if it was functioning before, because it just more or less seemed to go wherever. I think you will agree that the new behavior is much more intuitive when you try it.
> Hand tool improvements

- core_lib/structure/keyframe.cpp
- core_lib/structure/keyframe.h
- core_lib/structure/layer.cpp
+ Fixed an instance where removing the first frame would sometimes lead
to a crash. See #639 
- Removed unused keyframe header stuff.
> Fixed removing first frame would crash application #639

- .travis.yml
Since I’m playing with CI again, this makes it possible for me to have my own nightly builds, so I can check if everything works as intended. To keep the upload for this repo working as well, you’ll need to set two env vars in travis: 
- `LINUX_NIGHTLY_PARENT` = `0BxdcdOiOmg-CcU1WOFpCOFBvVXc`
- `OSX_NIGHTLY_PARENT` = `0BxdcdOiOmg-CeVpTY294cXdLZ2c`
> Specify Nightly target directories as env vars

- appveyor.yml
Okay, here goes the AppVeyor edition of #648. The env vars you need to set in AppVeyor for this repo are:
- `WIN32_NIGHTLY_PARENT` = `0BxdcdOiOmg-CcUEwS1R0WFhwM0E`
- `WIN64_NIGHTLY_PARENT` = `0BxdcdOiOmg-CSVlqc3JNQV9hVGs`
> Specify Nightly target directories as env vars, AppVeyor ver.

- app/mainwindow2.h
The window title timestamp should be stringified too, otherwise compilation fails.
> Apply STRINGIFY to window title TIMESTAMP

- app/mainwindow2.cpp
FIxed deleting current layer shortcut not working, related to #129
> #129 fix delete current layer shortcut not working

- core_lib/structure/filemanager.cpp
- core_lib/structure/layer.cpp
- core_lib/structure/layer.h
This PR fixes #555 which occurred when special characters were inserted into layer labels, causing your save to become corrupted.
It looks through all ascii characters, if the inserted character is above, then replace with '?'
> fix #555 replace special characters with '?'

- core_lib/canvasrenderer.cpp
It was mentioned in #552 that some time ago, whenever you selected a camera layer, everything would be shown "as if rendered" 
Prior to this PR only the selected layer would be shown fully opaque.
demonstration of the PR:
> fixed an issue that would render layers translucent on a camera layer

- .travis.yml
In 685a0d7729543834db607ee63957eef5aaa4b9c0, the output directory of the Pencil binary was changed from app/ to bin/, but the Travis build script was not updated accordingly, causing Linux and macOS nightlies to be generated without the binaries as mentioned in https://github.com/pencil2d/pencil/pull/633#issuecomment-299073279 – This PR makes up for that. The change also means that removing the Makefile is no longer necessary.
> Fix packaging on Travis after binary target dir changed

- app/actioncommands.cpp
- app/filedialogex.cpp
- app/filedialogex.h
- app/mainwindow2.cpp
While working on #673 I noticed that sound import and movie export used the file dialog from filedialogex.(h|cpp) while all the other import/export/open/save procedures each did their very own thing. Therefore I adapted FileDialog accordingly and replaced the remaining QFileDialogs with it. This will make #673 much easier for me and it improves consistency. Also, translatable default file names!
Right now there are still two todos left in the code, I’ll resolve them as part of #673 because it’s easier that way.
> Always use FileDialog instead of QFileDialog

- core_lib/interface/scribblearea.cpp
- core_lib/tool/brushtool.cpp
- core_lib/tool/penciltool.cpp
- core_lib/tool/pentool.cpp
- core_lib/tool/strokemanager.cpp
This fixes #677 #678
Notice though that pressure still won't do anything for brush unless feather is on. I recall it was discussed whether Brush should have size pressure or not and I believe that it concluded that pressure should only affect feather at the time.
Because of that and the fact that there's no constant control for feather blending, it feels a bit broken. Therefore whenever you need feather, set pressure on too, otherwise it won't work. I want to add more customisation for the tools but I don't want to implement anything yet if we intend to integrate mypaint.
> fixed brush dap artifact and pressure toggle

- .gitattributes
What it says in the title; pretty trivial. See <https://github.com/github/linguist#vendored-code> for documentation of this feature.
> Make GitHub exclude code in 3rdlib/ from language statistics

- core_lib/managers/toolmanager.cpp
I caught another compiler error that I originally missed because it appears to be specific to MSVC. The parameter type of ToolManager::setTolerance was changed from qreal to int, but the isnan check on the parameter was not removed, so the compiler didn’t know whether it should cast the parameter to float, double or long double. Since int can never be NaN to begin with, I removed the check.
> Fix compilation with MSVC 12.0

- app/aboutdialog.cpp
Just something that I happened to run across due to https://github.com/pencil2d/pencil/issues/622#issuecomment-311619489. Better ~safe~ correct than sorry
> About dialog links to GPLv3, should actually be GPLv2

- app/mainwindow2.cpp
- core_lib/interface/editor.cpp
- core_lib/interface/editor.h
- core_lib/interface/timecontrols.cpp
- core_lib/interface/timecontrols.h
- core_lib/interface/timeline.cpp
- core_lib/interface/timeline.h
- core_lib/structure/filemanager.cpp
When opening an animation, load the "currentFPS" value if present. For example if the saved file has:
<currentFps value="12"/>
...then set the FPS value in the editor to 12.
This will save me having to remember and adjust the FPS each time (I usually have a sound-track timed to a certain fps).
Video below (apologies, this runs quite slow):
[load-fps-value-video.zip](https://github.com/pencil2d/pencil/files/1125805/load-fps-value-video.zip)
> Load the FPS value when opening an animation

- app/colorpalettewidget.cpp
- app/colorpalettewidget.h
The main widget background is back to white, while the individual color swatches have a checkered background which is visible for transparent/translucent colours like so:
This is an alternative approach to #698. (@martinvanzijl Sorry, I'm not trying to compete with/upstage you 😛  I just think this is a better solution to the ugly background as it displays translucent colours better).
Edit: Woot, got #700 🎉
> Update color palette background

- .travis.yml
- appveyor.yml
See [`1d67de0` (comment)](https://github.com/pencil2d/pencil/commit/1d67de0751e1b91bc0ee765a2ab6f73a58f65ff1#commitcomment-22953496). The way I implemented it, nightly builds can still be uploaded by setting the environment variable FORCE_NIGHTLY_UPLOAD to yes (because that’s what I want).
> Upload nightly builds only from master branch or when forced

- 3rdlib/quazip/quazip.pro
- core_lib/interface/recentfilemenu.cpp
- core_lib/interface/recentfilemenu.h
Now there's a 'Clear Menu' item in the recent files submenu that functions similarly to the preferences button added in #686, except in a better place.
> Add Clear Menu item to recent files list

- core_lib/interface/recentfilemenu.cpp
- core_lib/interface/recentfilemenu.h
The call to QMenu::clear() wasn’t doing anything we didn’t do ourselves anyway except for deleting QActions we still needed. Instead we are now simply removing the clear actions without deleting them right away.
> Fix segfault when repopulating RecentFileMenu after clearing it

- app/mainwindow2.cpp
- app/mainwindow2.h
- core_lib/managers/preferencemanager.cpp
- core_lib/managers/preferencemanager.h
- core_lib/util/pencildef.h
This adds an action to the Windows menu that can be toggled to prevent the QDockWidgets from being dragged around or popped out.
Requested by Charmly here:
http://www.pencil2d.org/forums/topic/is-there-a-way-to-lock-the-windows/
Edit: Also thanks @Jose-Moreno for bringing this one to my attention with the Pencil document.
> Add option to lock widget positions

- app/mainwindow2.cpp
- core_lib/managers/playbackmanager.cpp
- core_lib/managers/playbackmanager.h
Noticed while reviewing #708, but of course only after it had already been merged.
> Disbale typo

- app/tooloptionwidget.cpp
- core_lib/canvasrenderer.cpp
- core_lib/canvasrenderer.h
- core_lib/graphics/bitmap/bitmapimage.cpp
- core_lib/graphics/bitmap/bitmapimage.h
- core_lib/interface/scribblearea.cpp
- core_lib/interface/scribblearea.h
- core_lib/managers/toolmanager.cpp
- core_lib/tool/buckettool.cpp
Floodfill algorithm has been rewritten from scratch.
New:
+ Filling outside a figure (or on a empty canvas) will lead to filling the size of the camera, the effect is similar to that of filling a fixed canvas in a painting application.
+ Support alpha values
Edits:
+ rephrased tolerance tooltip
+ set default tolerance to 10
Remaining issues?
When you click outside the camera area, filling the empty space, the fill behaviour will become similar to the old algorithm, filling a temp rect. It's a minor issue, but I thought I would mention it anyway.
> Flood Fill algorithm rewritten

- core_lib/external/macosx/macosx.cpp
- core_lib/tool/stroketool.cpp
I believe that this will solve the brush lag that people have been
reporting on 10.12 lately. Given that coalecing would never be activated on anything but 10.11
> Check if current OSX version is above or equal to ElCapitan

- core_lib/interface/scribblearea.cpp
- core_lib/interface/scribblearea.h
note: this only occurred when selecting vector curves.
> fix selection rect not being removed when pressing backspace

- app/mainwindow2.cpp
- core_lib/interface/scribblearea.cpp
- core_lib/interface/scribblearea.h
- core_lib/tool/basetool.cpp
- core_lib/tool/basetool.h
- core_lib/tool/brushtool.cpp
- core_lib/tool/erasertool.cpp
- core_lib/tool/penciltool.cpp
- core_lib/tool/pentool.cpp
- core_lib/tool/polylinetool.cpp
- core_lib/tool/smudgetool.cpp
Circle cursor is now drawn only within canvas area, see #655
Also changed such that cursor size is affected by zooming.
You can see the difference below:
> Draw circle cursor within canvas area

- app/actioncommands.cpp
- app/actioncommands.h
- app/mainwindow2.cpp
- core_lib/interface/editor.cpp
- core_lib/interface/editor.h
- core_lib/interface/scribblearea.cpp
- core_lib/interface/scribblearea.h
implemented for #723 
Because of the way applyTransformedSelection works atm. deselectAll is required for the transformation to be set properly and will therefore remove the selection rectangle upon clicking one of the options. I would like to change that behaviour but simply lack the knowledge of how these selections are applied right now. Maybe this is why most drawing applications has a "Transform" state（￣ ー￣)... food for thought.
> Flip selection along x and y axis

- core_lib/managers/playbackmanager.cpp
- core_lib/managers/playbackmanager.h
fixes #733
Changes on the timeline made while playback is on, are not updated until it has been stopped again.
This can cause various problems that may crash the program. 
A simple solution could be to stop playback whenever you click on the timeline.
> Fixed sound not starting over when loop is active

- .travis.yml
- appveyor.yml
- util/checkchanges.sh
This should avoid making duplicate builds when changes are not related to source code.
> Travis and AppVeyor should ignore certain files

- util/checkchanges.sh
It will still output fail because the build doesn't succeed. As far as I know, there is no way to get successful when you cancel the build early.
> removed travis_terminate as it doesn't work for some reason

- core_lib/interface/editor.cpp
- core_lib/interface/editor.h
- core_lib/managers/playbackmanager.cpp
- core_lib/managers/soundmanager.cpp
- core_lib/managers/soundmanager.h
- core_lib/structure/layer.cpp
- core_lib/structure/layersound.cpp
- core_lib/structure/layersound.h
- core_lib/structure/soundclip.cpp
* duplicate for sound frames
* made sound frames slightly transparent to be able to see overlapping sound tracks
* typos? referring to these `if ( !key->fileName().isEmpty() ) { return Status::FAIL; }` which made no sense before... not empty == fail? how does that make sense O_o
* refactoring.
It should be possible to duplicate frames to the current scrub position by selecting a frame and clicking duplicate. Atm. you are required to have the scrubber within the frame you want to duplicate.
> Implemented duplicate for sound frames.

- util/checkchanges-win.ps1
I noticed Appveyor failed on a source commit, not sure why though, given the setup of the script I would assume that Global and Script would have the same scope but apparently not. This is my first PowerShell script, so I just experiment until something seems to work, apologies. 
I've tested this against multiple random source files now and it worked as expected, so hopefully this won't require more changes.
> more ps1 changes..

- app/actioncommands.cpp
- core_lib/interface/backupelement.h
- core_lib/interface/editor.cpp
- core_lib/interface/editor.h
Lo and behold! you can now undo frame deletions.
This is related to #748, #36 
Because of the way the timeline works with 1 frame being required on a layer, you can't restore a soundclip if it overlaps the first empty frame.
> Implemented UNDO frame deletion for Bitmap, Vector and Sound

- app/tooloptionwidget.cpp
- app/tooloptionwidget.h
- core_lib/managers/toolmanager.cpp
- core_lib/managers/toolmanager.h
I found the unlabeled radio buttons to be very user-unfriendly. Unless you think to hover over it, there is no way to tell which radio button is for higher or lower interpolation levels. Having a combo box that uses the label text instead is a much better option. It looks like this now:
Even better would be to have a icon button set, something similar to this:
Or to have a slider control over the specific weighting of the interpolation. But since we are in the middle of the RC phase right now, I didn't want to mess with this any more than I had to.
> Use combo box for line interpolation

- pencil2d.desktop
This had to be done because linuxdeployqt can't handle higher versions at the moment (see errors here: https://travis-ci.org/chchwy/pencil2d/jobs/297832888#L1602-L1603). The Keyword key had to be removed because it is not supported by version 1.0.
Fixes #779.
[See successful travis build with this change](https://travis-ci.org/scribblemaniac/pencil/builds/297848345)
> Downgrade linux desktop entry file to version 1.0

- .travis.yml
- pencil2d.desktop
Travis really gotta update their Ubuntu, I tell you.
Luckily, though, impact on build time is hardly noticeable, since desktop-file-utils is so small.
> Fix nightly AppImages (again)

- core_lib/structure/filemanager.cpp
Add check when saving if parent directory exists and if it is writable for better error messages. Pretty sure I didn't screw it up this time 😥
> Fix error report when making a new file in a read-only directory

- app/actioncommands.cpp
- core_lib/interface/timecontrols.cpp
- core_lib/managers/playbackmanager.cpp
- core_lib/managers/playbackmanager.h
Hello!
I'm a member of the Pinguem.ru competition on finding errors in open source projects.
I found an issue with Pencil playback where you can make playback state in out of sync with the range-playback controls. It is especially noticeable when you work with a sound. To reproduce the bug please follow steps:
- Create new sound layer with `Ctrl+Alt+W` shortcut;
- Add new frame by pushing `Keys: Add Frame (+)` button;
- Choose an audio file;
- Push `Loop` button (just for convinience);
- Push `Play` button;
- While playing try to trigger `Range` box or change `Strat of playback loop`/`End of playback loop` spinbox values — you'll see no difference in playback behaviour, it'll still play with old settings even after end of a loop iteration. But at the same time graphical range indication …
> Proper playback update on range controls change

- .travis.yml
- util/checkchanges-win.ps1
- util/checkchanges.sh
Basically linuxdeployqt has a version of desktop-file-validate embedded in it which it copies from the version embedded in appimagetool, which happens to only validate 1.0 desktop files ([and it does not appear that they plan on changing this any time soon](https://github.com/AppImage/AppImages/issues/166#issuecomment-343829147)). What this change does is extract the linuxdeployqt continuous build AppImage to an AppDir, update the desktop-file-validate version inside it, then convert it back to an AppImage and run it. As you can see [here](https://travis-ci.org/scribblemaniac/pencil/jobs/306231748#L1755), we are no longer getting the errors with desktop-file-validate, so everything should work properly.
Fixes #779 (yet again).
> Fix Linux AppImage build

- app/main.cpp
- core_lib/interface/editor.cpp
- core_lib/interface/editor.h
Additionally, I
- made sure all CLI output goes directly to stdout rather than through qDebug() (since the latter can be disabled at build time)
- Put the logic for ignoring -NSDocumentRevisionsDebugMode into handleArguments()
- Shifted some code around so the program is only fully initialized once it’s actually needed (i.e. no need to have a complete MainWindow2 constructed (which takes time) if the user is just running `Pencil2d -h`)
> Allow movie export from command line

- core_lib/managers/viewmanager.cpp
- core_lib/managers/viewmanager.h
extending the implementation of fixed zoom levels in https://github.com/pencil2d/pencil/commit/0cadf70d2b97590185e570cedf3b330dba6c7c0b for zoom shortcuts.
> Re-added old zoom levels

- app/mainwindow2.cpp
- app/mainwindow2.h
* Fixed cancel dialog button being ignored.
* Fixed save dialog appearing twice when quitting from dock on OSX 
* The problem is caused by a bug in Qt, so for now i’ve added a simple
workaround. See: https://bugreports.qt.io/browse/QTBUG-43344
> fixed save, open and quit dialog issues

- core_lib/interface/scribblearea.cpp
- core_lib/interface/scribblearea.h
- core_lib/tool/basetool.cpp
- core_lib/tool/basetool.h
- core_lib/tool/penciltool.cpp
- core_lib/tool/penciltool.h
*  fixed an issue that could make dotted cursor stall application.
It would only happen whenever dotted cursor was enabled and you zoomed
too close with a huge brush. An example would be > 150 brushWidth and + 4000% zoom.
* Fixed feather cursor visual would be shown even though feather is off.
Additionally I’ve also made canvasCursor and quickSizeCursor static.
> dotted cursor improvement and fixes

- .travis.yml
I tried to get the formula from git but homebrew just kept ignoring it, now grabbing directly from githubs raw https.
> get Qt 5.9 from history, since homebrew updated to 5.10

- core_lib/movieexporter.cpp
- core_lib/movieexporter.h
I was content to wait for #681, however since there were already attempts to improve the current exporting lately (ac5e19f, 17bff13), I thought I would take a moment to finish this up. GIF export is now greatly improved, no more video artifacts. Based on my tests, it is visually identical to ImageMagick's GIF export and looks about as good as GIFs possibly can.
Closes #818
> Improve GIF export quality by removing first pass conversion to mp4

- core_lib/canvasrenderer.cpp
- core_lib/canvasrenderer.h
- core_lib/graphics/bitmap/bitmapimage.cpp
- core_lib/graphics/bitmap/bitmapimage.h
- core_lib/interface/scribblearea.cpp
This will properly downscale the canvas when the view is below 100%
I've been trying to get it to work when zooming in too, but the way the renderer currently works makes it impossible as the canvas has to be upscaled a lot and qimage is not made for that.
When we migrate to myPaintLib, I will look into this again, because its renderer splits the canvas up into smaller sections and therefore should provide the solution we need to make that work.
This will additionally also make it possible for us to prescale the brush stroke, so the representation will have the same look.
> properly downscale canvas when zooming out

- core_lib/canvaspainter.cpp
The problem occurred here https://github.com/pencil2d/pencil/commit/fac2c762c8ecaf4246369fc851c9a93bdce21271
when my transform was accidentally reversed :P 
So basically what caused the lag here is that the canvas got upscaled A LOT and then downscaled again (by the painter) to get a good subsampled picture. This is not a problem when the image is small but when it becomes 50x larger then it gets hairy because it's trying to allocate a huge image in memory (in case of 96x scale) that has to be made for each time it's being asked to zoom the canvas.
> Fix ram consumption and lag when zooming out 

- appveyor.yml
Apparently AppVeyor recently switched from 5.9.2 to 5.9.3 which broke builds for me. With this, our build will always use whatever version of the 5.9 release is currently available on AppVeyor.
> Switch AppVeyor from 5.9.2 to 5.9.x

- .travis.yml
- pencil2d.desktop
This should allow us to use linuxdeployqt without any modifications. Replaces #823.
> Patch desktop entry to be version 1.0 in AppImages

- app/DoubleProgressDialog.ui
- app/actioncommands.cpp
- app/app.pro
- app/doubleprogressdialog.cpp
- app/doubleprogressdialog.h
- core_lib/interface/editor.cpp
- core_lib/movieexporter.cpp
- core_lib/movieexporter.h
In addition to the main progress bar, a second progress bar and a
label have been added to display subtasks of the exporting. Not only
does this better show progress, but it also makes reports about
freezing/crashing during export more useful (ex. "it says Generating
Palette and then crashes").
The ffmpeg execution code was modified to detect the progress
of the operation. This also fixes a hidden serious bug with movie
exporting: waitForFinished has a timeout of 30 seconds by default,
so any movie that takes longer than that to export would timeout
and fail. This should hopeful fix some of the exporting errors
we've been seeing. waitForReadyRead also has a timeout (default 30s
I think), but this isn't an issue because FFmpeg will write updates
and flush every second or so, returning …
> Improve movie export dialog

- core_lib/interface/backgroundwidget.cpp
- core_lib/interface/scribblearea.cpp
Just a small modification to limit the background styling to the background widget. Prevents stuff like this from happening:
> Fix background in hidden layer warning dialog

- app/ui/errordialog.ui
- app/ui/mainwindow2.ui
- core_lib/graphics/vector/beziercurve.cpp
- core_lib/interface/timecontrols.cpp
- core_lib/interface/timeline.cpp
- core_lib/interface/timelinecells.cpp
- core_lib/structure/layer.cpp
- core_lib/structure/object.cpp
The html property in errordialog.ui was overridden from the code anyway, so I removed it completely. The other changes should be quite self-explanatory. Resolves #874.
> Remove hardcoded fonts

- core_lib/graphics/vector/beziercurve.cpp
Fix for issue #739. Now draws vector outlines as expected when "Show Outlines Only" and "Horizontal Flip" are enabled.
Video below:
> Fix for issue #739

- app/mainwindow2.cpp
- core_lib/graphics/bitmap/bitmapimage.cpp
- core_lib/interface/scribblearea.cpp
- core_lib/structure/layercamera.cpp
- core_lib/tool/eyedroppertool.cpp
- core_lib/tool/handtool.cpp
- core_lib/tool/movetool.cpp
- core_lib/tool/selecttool.cpp
See #890, also compiler warnings. First commit was tested on Ubuntu Xenial only, but since the symptoms were the same I suppose the fix should also work on Debian Stretch.
> Various fixes

- docs/build_linux.md
Mainly added instructions for Arch Linux and changed the instructions to use out-of-source builds since those are generally recommended these days (for good reason). Also some minor fixes. I removed some of the qt packages from the apt install line for Ubuntu since I believe they are unnecessary (and I was able to compile the program without them) but if there’s indeed a reason for installing those as well that I’m not aware of please let me know.
> Revise Linux compilation guide

- .travis.yml
- Doxyfile
As the title says. For the tag file location I used util/ and the system documentation locations for Ubuntu and Arch, Doxygen will skip the ones that do not exist and the first one found will take precedence. Tag files in util/ are assumed to belong to Qt’s online documentation (downloaded when documentation is deployed, for instance), the other ones will be linked to local documentation. If Qt also has a standard documentation path that can be relied on on Windows and/or OS X, adding those would probably be a good idea, too.
> Link API documentation to Qt documentation

- core_lib/src/interface/timecontrols.cpp
- core_lib/src/interface/timecontrols.h
Fixes #851. This works for me on Ubuntu 14.04.
The connection from the FPS spin-box is set up here:
`connect(mFpsBox, spinBoxValueChanged, this, &TimeControls::fpsClick);`
The Application Output tab showed a warning that the connection was not valid. I added a breakpoint to "fpsClick" and changed the FPS value, but "fpsClick" was never called. 
I tried a couple of other things (from https://stackoverflow.com/questions/16794695/connecting-overloaded-signals-and-slots-in-qt-5/16795664) but couldn't get the valueChanged signal to work. 
So finally I changed it so that if the "spinBoxValueChanged" connection is invalid, we use the "editingFinished" signal instead.
> Fix #851. Make sure the FPS spin-box works on Linux.

- app/src/mainwindow2.cpp
- app/src/mainwindow2.h
Fix for #857. Adds a progress dialog when importing image sequences, just like the one for exporting.
Note: The auto-save prompt is disabled while doing the import.
.
> Progress bar for importing image sequences

- app/src/main.cpp
A temporary solution for high DPI displays by setting `Qt::AA_EnableHighDpiScaling`.
I test it on an 15-inch MacBook Pro with Win 10 installed, resolution 2800x1800, 200% display scaling.
1. `Qt::AA_EnableHighDpiScaling` On:
Generally it's fine, but take a closer look at the play and add-key button, you will see pixelated icons.
2. `Qt::AA_EnableHighDpiScaling` Off (as 0.6 official build)
Very tiny icons, and overlapped font on Timeline
It's not a perfect solution but will make the Pencil2D UI *usable* on a 4k monitor.
> A temporary solution for high dpi displays

- core_lib/src/graphics/bitmap/bitmapimage.cpp
As a result of https://github.com/pencil2d/pencil/commit/ad8393733ad950ab1c3d178a559b062d5119148e
this was re-introduced https://github.com/pencil2d/pencil/issues/510
This PR should fix that by making sure that the pixel is transparent.
@chchwy maybe this should be applied as a 0.6.1.1 hotfix?
> Fix 1x1 pixel dot appearing in center of canvas.

- app/src/mainwindow2.cpp
- core_lib/src/util/pencildef.h
strImgFileLower was only used as a mean to check the file extension but never used with importImage(QString). The if statement is unnecessary because we filter the allowed file formats to be imported via pencildef.h
Prior to this, if the file format was read as invalid from the if statement, the for loop would simply continue. This could lead to files not being imported correctly.
I've also removed .tiff format because it doesn't appear to be working.
> Remove .tiff (doesn't work) and add warning if file is not imported

- app/src/preferencesdialog.cpp
- app/src/preferencesdialog.h
- app/ui/timelinepage.ui
- core_lib/src/interface/scribblearea.cpp
- core_lib/src/interface/scribblearea.h
- core_lib/src/managers/preferencemanager.cpp
- core_lib/src/managers/preferencemanager.h
- core_lib/src/tool/movetool.cpp
- core_lib/src/tool/polylinetool.cpp
- core_lib/src/tool/smudgetool.cpp
- core_lib/src/tool/smudgetool.h
- core_lib/src/tool/stroketool.cpp
- core_lib/src/tool/stroketool.h
- core_lib/src/util/pencildef.h
Fixes a "vanishing line" bug in Bitmap layers. To reproduce the issue:
1. Create a new animation.
2. Select the Bitmap layer.
3. Go to frame 2.
4. Draw a line with the pencil, pen or brush tool.
5. The line will "disappear".
Video demos below before and after the fix.
> [Feature] Options when drawing on an empty key-frame

- core_lib/src/interface/scribblearea.cpp
- core_lib/src/interface/scribblearea.h
- core_lib/src/tool/movetool.cpp
- core_lib/src/tool/movetool.h
- core_lib/src/tool/selecttool.cpp
- core_lib/src/tool/selecttool.h
Fixes the selection rectangle disappearing when overlapping origin edges.
Affects: MoveTool and SelectTool
> Fix selection rectangle disappearing

- app/src/mainwindow2.cpp
This is a small change that moves the color inspector to the right (under the color wheel) to match with the location of the sliders before they were made into a new widget. The display widget was moved to the left to balance the sides out. It should look like this now by default:
I think this is a much better setup because it has all of the color stuff on the right and all the tools/settings on the left.
> Rearrange default dock widget locations

- app/src/actioncommands.cpp
- core_lib/src/interface/timeline.cpp
- core_lib/src/interface/timelinecells.cpp
This changes the behavior of the automatic timeline extension so that the length extends by 50% when you add a frame in the last 25% of the current timeline. This should make it much less noticeable. Before you would always be working on the very end of the timeline if you did not extend the timeline length manually.
It also also updates the length when frames are moved to the end now.
> Improve timeline length updating

- core_lib/src/graphics/bitmap/bitmapimage.cpp
- core_lib/src/graphics/bitmap/bitmapimage.h
This is all from #837. The relevant section from there:
> Inspired by how Krita does flood filling, I have added a hash map to remember if colors are within the threshold for the duration of the operation (threshold and oldColor will remain constant, so only newColor is needed for lookup). Since the vast majority of the pixels that will be encountered are usually from a small subset of colors, this should have significant speed benefits. The Euclidean difference operation is probably a bit slower than the old difference operation, so this is even more important.
Hmm, I wonder if this will work: Closes #837.
> Optimize bucket fill with cache

- core_lib/src/interface/scribblearea.cpp
- core_lib/src/structure/object.cpp
When the mouse is pressed, we expect there to be a frame either on the exact pos or a previous frame, if that's not the case, the key return as nullptr and therefore crash the application.
This PR fixes that problem by looking for the next index if a previous doesn't exist.
> Look for next frame if previous doesn't exist - #950

- app/src/colorpalettewidget.cpp
- app/src/colorpalettewidget.h
- app/ui/colorpalette.ui
- core_lib/src/graphics/vector/colourref.cpp
- core_lib/src/graphics/vector/colourref.h
- core_lib/src/managers/colormanager.cpp
- core_lib/src/structure/object.cpp
- core_lib/src/structure/object.h
I've fixed the remove button and added some enhancements.
* Add, replace or remove using right-click through the context-menu shown above
* Drag to select multiple color swatches
* no auto color update on palette anymore, use replace via context menu.
~~When palette is empty, vector layer will use front color instead of palette.~~
Known bugs:
modifying first index in palette, doesn't update vector stroke for some reason..
this is an old bug but I wasn't able to find the cause this time around.
Considering my proposal https://github.com/pencil2d/pencil/issues/962 that changes this, I'm leaving the bug as is for now.
> Fix remove color button and add context menu

- core_lib/src/tool/brushtool.cpp
- core_lib/src/tool/penciltool.cpp
- core_lib/src/tool/pentool.cpp
Fixes line interpolation being shared in some cases across tools.
Given that the changes are so small, I'm going to merge this myself.
> fix tool properties being shared in some cases

- app/src/actioncommands.cpp
- app/src/actioncommands.h
- app/src/exportmoviedialog.cpp
- app/src/exportmoviedialog.h
- app/src/filedialogex.cpp
- app/src/filedialogex.h
- app/src/importimageseqdialog.cpp
- app/src/importimageseqdialog.h
- app/src/mainwindow2.cpp
- app/src/mainwindow2.h
- app/ui/mainwindow2.ui
- core_lib/src/interface/editor.cpp
- core_lib/src/interface/editor.h
- core_lib/src/util/pencildef.h
Importing/exporting gif has been improved. #903
- Gif has been given its own option under file->Import and file->Export
- Spacing between frames now works for GIF
> Improve GIF UI/UX import/export

- app/src/actioncommands.cpp
- app/src/importexportdialog.cpp
- app/src/importexportdialog.h
- core_lib/src/movieexporter.cpp
* tweening didn't work for GIF exports ( hasn't worked since 0.6 apparently)
* fixed a bug that made the "open video" prompt not work when pressing yes. 
This was introduced via #1008 and discovered by @Jose-Moreno 
* Implemented "open file location" dialog for gif exports
> Export movie/gif fixes

- core_lib/src/graphics/bitmap/bitmapimage.cpp
- core_lib/src/structure/filemanager.cpp
- core_lib/src/structure/filemanager.h
- core_lib/src/structure/keyframe.h
- core_lib/src/structure/layerbitmap.cpp
- core_lib/src/structure/layerbitmap.h
- core_lib/src/util/pencilerror.h
This implementation contains the following
+ fixes that solves: #966 
+ A way to remove old data folder file references.
+ This happens currently before saving new files and after having saved new files, to avoid cases where a project contains old file references beforehand and when frames has been moved but the reference hasn't been deleted.
> Fix saving issue when moving frames

- app/src/colorpalettewidget.cpp
This includes:
- Showing the proper icon color when selected (Fixes #1024)
- Adding a border around the selected color, this is particularly
useful for grid mode which has no other way to display the selection
- Refactored the resizing code so that going to grid mode from list
mode does not result in unexpected icon spacing
> Improve color palette selection behavior

- app/app.pro
- app/data/_pencil2d
- app/data/pencil2d
A minor thing that’s been on my personal todo list since I last worked on our command line interface.
Right now the bash completion is noticeably more primitive than the zsh completion (mostly because bash’s completion system as a whole is noticeably more primitive than zsh’s) however both should be quite useful.
> Add completion for bash and zsh

- core_lib/src/interface/timeline.cpp
The issue:
1. Start pencil2d, the timeline length is 240 frames by default.
2. Open a 1000 frames project
3. Timeline length extends to 360 frames, which should be 1000 frames.
In the previous implementation, timeline grows 1.5 times longer based on the current length. But in this case, the timeline length must grow more.
Also, I changed the timeline extending rule. I think the previous 75% rule is a little too much for a long project. I work on a 1000 frames and timeline extends to 1500 frames when I create a keyframe at frame 750. 
The new rule is, Timeline will extend 100 more frames when a user adds a keyframe within 50 frames to the end of Timeline.
> Timeline didn't extend to a correct length when opening a super long project

- core_lib/src/structure/filemanager.cpp
- core_lib/src/structure/object.cpp
- core_lib/src/util/fileformat.cpp
- core_lib/src/util/fileformat.h
Related issues #932 #752  
The issue described by @scribblemaniac :
If a user opens the same project twice in a row, Penci2D will:
1. Create data folder for file to load
2. Load everything into the data folder
3. Stop if there is an error
4. Switch to using the new data folder
5. Delete the old data folder
However, if the old data folder and new data folder are the same, then step 5 ends up deleting all the data from our project! 
In order to resolve the name conflicts, the data folder will include an 8 character long random string.
For example:
- YourProject_Y2xD_6xseyd51
- Default_Y2xD_5zy4hsui
> Extract pclx to a random generated folder name to avoid name conflicts

- core_lib/src/graphics/bitmap/bitmapimage.cpp
- core_lib/src/graphics/bitmap/bitmapimage.h
- core_lib/src/interface/editor.cpp
- core_lib/src/interface/scribblearea.cpp
- core_lib/src/structure/layerbitmap.cpp
- tests/src/test_bitmapimage.cpp
This is a second attempt at what I did in #791. Quoting from there:
> Now the BitmapImage will automatically resize itself to be at the minimum size possible without cropping any data. This fixes the second issue of #774 and goes a step further to update the Select All bounding box when the edge is erased with an eraser, deleted with a selection clear, or brush strokes/flood fill with an alpha of 0 are applied. Since it resizes the image when necessary, this will also reduce the file size and speed up playback slightly whenever part of the minimum bounding box of an image decreases (most notably when moving the whole layer).
This has been optimized to prevent this feature from slowing down Pencil2D. The image should not be cropped at all until a brush stroke is finished so there should be …
> Reimplement autocropping

- core_lib/src/graphics/vector/vectorimage.cpp
- core_lib/src/tool/erasertool.cpp
The distance to points was being calculated incorrectly since the dot product produces the *square* of the eulerian distance. There were also differences in how the vector eraser width was being calculated compared to the bitmap tools (particularly, it takes into consideration the scaling, which we removed I think). Overall these fixes will make the vector eraser less broken, but I would not go as far as to say completely fixed.
Please test to make sure that the pressure is working reasonably as I don't have a tablet to test this with at the moment.
> Improve vector eraser tool

- core_lib/src/structure/filemanager.cpp
This string is also in the translation files, but I assume you have some automated thing to update those.
> fix typo, s/offical/official/

- app/src/actioncommands.cpp
- app/src/actioncommands.h
It is a hidden bug in Pencil2D, that users can have duplicate layer names.
It is unlikely that anyone would name their layers with the same name, but it should not be possible at all. This PR would mend this bug - as I call it.
> Small changes that can prevent users from duplicate layer names

- app/src/mainwindow2.cpp
- app/ui/exportimageoptions.ui
- core_lib/src/interface/editor.cpp
- core_lib/src/structure/object.cpp
- core_lib/src/util/pencildef.h
Had to change "while" to "if" on core_lib/src/interface/editor.cpp:754 because usage of 'while' relies on fact that QImageReader::read(QImage) doesn't reset position inside the image file which apparently ain't working with TIFF files ( QImageReader::read(QImage) always returns true for TIFF which results in infinite loop)
> #1068 added support for tiff import/export

- core_lib/src/interface/timecontrols.cpp
I've added two lines of code that set the spinboxes unabled at startup.
I have tried to open Pencil2D from command line, with a pclx-file as parameter. This file was saved with range set to 1-16, and that range was still active after loading the scene, so it works whether you open Pencil2D with or without a scene.
> issue 1101: Range spinboxes set uneditable at startup

- app/app.pro
- app/src/colorpalettewidget.cpp
- app/src/colorpalettewidget.h
- core_lib/core_lib.pro
- core_lib/src/graphics/vector/colourref.cpp
- core_lib/src/graphics/vector/colourref.h
- core_lib/src/structure/object.cpp
- core_lib/src/util/colordictionary.h
Modified the gpl importer to more closely match the behavior of GIMP as it was not working with some valid gpl files. Looked through the GIMP source and tested various edge cases. Also used the automatic naming function for any colors that do not have a name.
> Improve .gpl import

- app/app.pro
- app/src/main.cpp
- core_lib/core_lib.pro
- core_lib/src/external/linux/linux.cpp
- core_lib/src/external/macosx/macosx.cpp
- core_lib/src/external/macosx/macosxnative.h
- core_lib/src/external/macosx/macosxnative.mm
- core_lib/src/external/platformhandler.h
- core_lib/src/external/win32/win32.cpp
- pencil2d.pro
- tests/tests.pro
Newer versions of macOS add a "Show Tab Bar" option to the "View" menu automatically. Pressing it screws with the layout a little bit like this:
There is no way to remove the menu item with Qt, see [this bug report](https://bugreports.qt.io/browse/QTBUG-61707). To fix this I integrated a small amount of native objective-c code for mac builds.
This also enables us to easily add support for more native mac features in the future. I implemented mouse coalescing in this same way, but is currently not being used. It seems like what we are currently doing for setting mouse coalescing is not working, so when we actually disable it the brush stroke lags significantly similar to #1133. According to my event counter the peak number of events doubles from 128 to 256. This shouldn't cause a …
> Remove Show Tab Bar from the View menu on mac

- app/src/preferencesdialog.cpp
- app/src/preferencesdialog.h
- app/ui/timelinepage.ui
- core_lib/src/interface/timeline.cpp
- core_lib/src/interface/timeline.h
- core_lib/src/interface/timelinecells.cpp
- core_lib/src/interface/timelinecells.h
- core_lib/src/managers/preferencemanager.cpp
A zoom slider to change frame size. 
Values from 4 to 40. (Was 4 to 20).
For some reason it rearranges layout? Besides from that it works fine.
> Issue 1074. Slider to zoom framesize at timeline. Option removed from prefs.

- app/src/actioncommands.cpp
- app/src/actioncommands.h
- app/src/colorbox.h
- app/src/colorinspector.cpp
- app/src/colorinspector.h
- app/src/colorpalettewidget.h
- app/src/colorslider.cpp
- app/src/colorslider.h
- app/src/colorwheel.cpp
- app/src/displayoptionwidget.h
- app/src/doubleprogressdialog.cpp
- app/src/doubleprogressdialog.h
- app/src/errordialog.h
- app/src/exportmoviedialog.h
- app/src/importimageseqdialog.h
- app/src/mainwindow2.cpp
- app/src/mainwindow2.h
- app/src/preferencesdialog.h
- app/src/preview.h
- app/src/shortcutspage.h
- app/src/spinslider.cpp
- app/src/timeline2.h
- app/src/toolbox.h
- app/src/tooloptionwidget.cpp
- app/src/tooloptionwidget.h
This PR resolves most of the warnings in the app-directory.
Casts are changed from C to C++ style and '0' and 'NULL' is changed to 'nullptr'.
They are cast to the type the compiler would cast them to in the first place. 
Only in colorslider.h, I changed two member variables from 'float' to 'qreal'. This solved many warnings in itself.
> Master resolve warnings

- app/src/actioncommands.cpp
- app/src/exportimagedialog.cpp
- app/src/exportimagedialog.h
- app/ui/exportimageoptions.ui
- core_lib/src/interface/editor.cpp
- core_lib/src/structure/object.cpp
- core_lib/src/structure/object.h
The possibility to import by filename has been merged.
The feature here will make it possible to only export the keyframes from a layer. Thus you can easily reuse animation from one scene to another.
There are also a few warning resolves. Only 'NULL' -> 'nullptr'
> Export only keyframes possible in exportImageSequence

- appveyor.yml
As discussed in Discord I am hoping that this will be a fix for #677. Wait until Appveyor actually updates their image to use Qt 5.12 obviously, see appveyor/ci#2760.
> Update Qt version used by Appveyor to 5.12

- app/data/Info.plist
- core_lib/src/external/macosx/macosxnative.mm
This change comes from a discussion on Discord:
the story is that this commit https://github.com/pencil2d/pencil/commit/d6157526854b7f9cdb53528ec152f83b5010b86d
tried to fix some styling regarding Mojave dark mode. What I failed to see however is that the flag apparently already exists from Mac OS 10.13 and thus will throw this error if compiled on that target
>'NSAppearanceNameDarkAqua' is only available on macOS 10_14 or newer [-Wunguarded-availability-new]
return apperance.name == NSAppearanceNameDarkAqua;
^~~~~~ 
Thus my conclusion is that since there's no reliable way to determine whether the OS runs AquaDark aka. dark mode, and that it still has various layout bugs regarding it, we should force the standard light theme for now to make the experience as pleasant as possible.
it's …
> Force light theme on mac os

- core_lib/src/interface/editor.cpp
- core_lib/src/interface/recentfilemenu.cpp
- core_lib/src/interface/scribblearea.cpp
This PR resolved many of the warnings in the Interface folder, in core_lib.
Some warnings remain. In scribblearea.cpp alone there are 59 warnings concerning 'implicit conversions'. Someone should look at this one day. I'm not sure it's within my reach to decide whether Penci2D should use floats, doubles, qreals or what...
> Resolved warnings for NULL and old-casts

- app/data/Info.plist
- core_lib/src/external/macosx/macosxnative.mm
Compiles and runs just fine on macOS 10.13, still needs to be tested on macOS 10.14 with and without dark mode. Based on code from Chromium.
> Renable dark mode on macOS

- core_lib/src/structure/filemanager.cpp
Because the decimal character can be different depending on the locale of your system for certain languages, we set the locale before saving and resetting afterwards to make sure that the xml data is generated consistently across languages.
> #940 - Fix XML fields corrupting because of locale decimal types.

- app/src/filedialogex.cpp
This is consistent with how we handle all other import dialogs. Palettes are the only exports without a custom dialog so it is not so easy to compare it with the other settings, but it still seems reasonable to me. Can someone please test this on Windows to make sure it doesn't do anything stupid with the dialogs (especially the palette export dialog)?
> Make default file filter for palettes match all supported formats

- core_lib/src/interface/scribblearea.cpp
- core_lib/src/interface/scribblearea.h
- core_lib/src/tool/movetool.cpp
- core_lib/src/tool/selecttool.cpp
- core_lib/src/tool/strokemanager.cpp
Fixes full pressure stroke/reed issues again. Closes #677. Also fixes duplicate selection box under the same environment.
> Fix Jose's Issues

- core_lib/src/managers/playbackmanager.cpp
Fixes a bug that made Pencil2D to crash, if you pressed the timeline digits while a flipping was performed.
Changed the timing in flip inbetween slightly, while I was at it. It's better now.
> Issue flip

- core_lib/src/interface/scribblearea.cpp
- core_lib/src/interface/scribblearea.h
- core_lib/src/tool/polylinetool.cpp
> #950 - always make sure there's a keyframe when drawing

- app/src/actioncommands.cpp
- app/src/shortcutspage.cpp
- app/ui/timelinepage.ui
- core_lib/src/interface/editor.cpp
- core_lib/src/interface/editor.h
- core_lib/src/interface/scribblearea.cpp
- core_lib/src/structure/layerbitmap.cpp
- core_lib/src/tool/buckettool.cpp
- core_lib/ui/camerapropertiesdialog.ui
Here's my second set of bugfixes for v0.6.4, same deal as last time. c0af82a was the last big issue I wanted to fix. Lots of issues remain, mostly vector or selection tool related, but they can wait.
~~e1db3a7 will probably be partially undone by #1211 and will require some extra attention after merging both of these PRs.~~ Edit: #1211 No longer conflicts with my changes here.
> Bugfixes 2

- appveyor.yml
I have tested the 64-bit binaries from https://indy.fulgan.com/SSL/ with v0.6.3 of Pencil2D and this fixes the Updater error on Windows 10.
Fixes #1195
> Add OpenSSL .dlls to enable https requests

- core_lib/src/miniz.cpp
- core_lib/src/miniz.h
Just got a bug report from the user forum
https://discuss.pencil2d.org/t/miniz-error-doesnt-let-me-record/3755/11
I can confirm the current v0.6.4 will fail to open any .pclx if the filename contains Unicode characters.
The issue is caused by the miniz update. We used to use a modified version of miniz to handle Unicode on Windows (Opening a file by `_wfopen_s()` rather than `fopen_s()`). But the change was overwritten when updating to miniz 2.1.0.
We might need to prepare a hot-fix release as soon as possible for that.
If anyone needs an example, please download this pclx:
https://www.dropbox.com/s/zgzp1vbscykspsb/%E8%A8%B1%E5%8A%9F%E8%93%8B.pclx?dl=0
> Fail to open a pclx with Unicode filenames on Windows

- core_lib/src/interface/scribblearea.cpp
- translations/pencil_zh_CN.ts
fix 2 chinese translation errors
> Fix translate bug. Fix a warning

- app/ui/colorinspector.ui
The spinbox in color inspector is too small.  
I set the mini width of the spinboxs to 55 instead of 0 can fix it.
old:  
new:
> make spinbox bigger

- core_lib/src/graphics/bitmap/bitmapimage.cpp
- core_lib/src/graphics/bitmap/bitmapimage.h
This PR is rather simple. It adds a function to BitmapImage, that replaces all pixels inside mBounds with a chosen color.
I think it is a good general-purpose function, and I know I can use it in one of the features I'm working on, + the bitmap-coloring feature + two more features I plan to work on.
Could it be merged right away, it would be easier for me, since I don't have to wait for a more complex PR to be accepted and merged, before the function is in the code base.
> Add function to fill non alpha pixels

- app/ui/filespage.ui
- app/ui/generalpage.ui
- core_lib/src/managers/preferencemanager.cpp
- Autosave max. value set to 8192 in filespage.ui
- Autosave initial value set to 256 in preferencemanager.cpp (this will provide an average of about 5~7 minutes of uninterrupted drawing before the autosave alert kicks in)
- Grid W & Grid H minimum values set to 1px in generalpage.ui
If there's a mistake or a missing alteration that needs to be made please point it out descriptively as usual. Thanks :relaxed:
> Autosave & Grid preference settings adjustment

- app/src/mainwindow2.cpp
- app/src/preferencesdialog.cpp
- app/src/preferencesdialog.h
- app/ui/toolspage.ui
- core_lib/src/interface/timeline.cpp
- core_lib/src/interface/timeline.h
We all should be well aware by now of how much confusion that "onion skin" button in the timeline is. Well now it's in the preferences with the other onion skin options and has been better described so there should be no more confusion.
Eventually this will be superceded by #1125, but I think this is a good short- to mid-term solution until an onion skin panel is implemented.
> Move onion skin mode selector to the preferences window

- app/src/colorinspector.cpp
- app/src/tooloptionwidget.cpp
- core_lib/src/interface/timecontrols.cpp
- core_lib/src/util/util.cpp
- core_lib/src/util/util.h
Created a helper function to connect the signal that spin boxes emit when enter is pressed to a function that removes their focus. Should allow all keyboard shortcuts to work after pressing typing in any of the spin boxes and pressing enter.
Fixes #1230
> Fix all spin boxes maintaining focus after returning

- core_lib/src/canvaspainter.cpp
- core_lib/src/interface/timelinecells.cpp
- core_lib/src/structure/layer.cpp
- Fix onion skin rendering below lower layers
- Fix previous onion skin display when on a held frame in absolute mode
- Fix next onion skin behavior when before the first frame in absolute mode
Fixes #989
> Fix onion skin rendering and behavior

- core_lib/src/interface/timelinecells.cpp
- core_lib/src/interface/timelinecells.h
This PR see to it, that the scrubber always is visible during playback.
It is a rather simple solution, since we shouldn't do too complicated things on the timeline, while we wait for the Timeline rewrite.
This one has bugged me (and @Jose-Moreno) and possible others for some time, so here is a solution.
> #1105 Added checks on timelinecells, so scrub is tracked

- app/app.pro
- app/src/importlayersdialog.cpp
- app/src/importlayersdialog.h
- app/src/mainwindow2.cpp
- app/src/mainwindow2.h
- app/ui/importlayersdialog.ui
- app/ui/mainwindow2.ui
- core_lib/src/structure/object.cpp
- core_lib/src/structure/object.h
The ability to reuse animation is essential today. Not just characters, but also rain, snow and other effects can be reused.
This PR makes it possible to import layers from whatever *.pclx file you want.
I don't think the import should be in the undo/redo, since it doesn't affect the other layers, and it's easy to delete layers if you want.
It's not a huge PR, but I think it's impact will be...
> Layer import, from *.pclx to active project

- app/src/mainwindow2.cpp
- core_lib/src/interface/recentfilemenu.cpp
- core_lib/src/interface/recentfilemenu.h
Hi, this is my proposal for opened Issues #1278 and #1279 .
> Fixing recent file menu issue #1278 and #1279

- app/src/tooloptionwidget.cpp
- app/ui/tooloptions.ui
This closes #1193 and #1194 .
Since the value indicates the alpha-value of the feathering, 100 = invisible. For this reason it could be argued that we should have 99 as maximum. Right now it is set to 100.
> #1193 Changing feather range to 1-99

- app/src/colorwheel.cpp
- core_lib/src/tool/selecttool.cpp
Just a fix of some compiler warnings (unused variable/arguments).
The only remaining warnings are in `miniz.h` and `miniz.cpp`, but these look to be third party.
> Miscellaneous compiler warning fixes

- app/app.pro
- app/src/importexportdialog.cpp
- app/src/importexportdialog.h
- app/src/importimageseqdialog.cpp
- app/src/importimageseqdialog.h
- app/src/importpositiondialog.cpp
- app/src/importpositiondialog.h
- app/src/mainwindow2.cpp
- app/src/mainwindow2.h
- app/ui/importexportdialog.ui
- app/ui/importpositiondialog.ui
- core_lib/src/managers/viewmanager.cpp
- core_lib/src/managers/viewmanager.h
This addresses #1177, but I won't say it closes it.
There are 3 kinds oh image imports:
(1) image - (2) image sequence - (3) predefined set.
With this PR, you can select whether you you want to import (2) and (3) relative to: 
(a) current view - (b) canvas centre - (c) current camera view. 
The selection is done in a combobox on the filedialog.
You can't select where you want to import a single image (1), because we use the ordinary fileopen dialog in that case, and it's not possible to (for me at least) to place a combobox on that dialog. It could be solved by agreeing that all single image imports are done to canvas centre. Or - what do you think?
You can't select camera either, if you have multiple cameras. The importExportDialog doesn't know of layers or editors, and I'm not convinced …
> #1177 Import drawings on wanted position

- app/src/actioncommands.cpp
- app/src/mainwindow2.cpp
- app/ui/displayoption.ui
- app/ui/exportimageoptions.ui
- app/ui/exportmovieoptions.ui
- app/ui/toolboxwidget.ui
- core_lib/src/canvaspainter.cpp
- core_lib/src/graphics/vector/beziercurve.cpp
- core_lib/src/graphics/vector/beziercurve.h
- core_lib/src/interface/editor.cpp
- core_lib/src/interface/scribblearea.cpp
- core_lib/src/interface/scribblearea.h
- core_lib/src/managers/layermanager.cpp
- core_lib/src/managers/soundmanager.cpp
- core_lib/src/structure/layersound.cpp
- core_lib/src/tool/brushtool.cpp
- core_lib/src/tool/erasertool.cpp
- core_lib/src/tool/erasertool.h
- core_lib/src/tool/polylinetool.cpp
- core_lib/src/util/pointerevent.cpp
- core_lib/src/util/pointerevent.h
Here are a bunch of bugfixes, almost all for unreported bugs. The commit messages describe what each of the changes are for, feel free to ask for clarification on any of them if needed. I recommend reviewing commit-by-commit as it will make much more sense than looking at all of the changes at once.
> Miscellaneous bugfixes

- appveyor.yml
- util/after-build.ps1
I rewrote the Appveyor after-build tasks by Powershell.
The behaviour is exactly the same as the previous packing process:
1. Download FFmpeg
2. Pack and zip binaries
3. Uploading to Google drive
A few benefits of using PowerShell scripts:
1. I can run and test the script locally on my machine without AppVeyor environment.
2. It's easier to implement features with a decent script language.
3. Built-in zip & wget, so we don't need 3party programs like`curl.exe` and `7z.exe` to pack binaries.
The next step I will implement internal PR builds for windows, which was once implemented and then was reverted.
> Rewrite the windows after-build tasks by Powershell

- app/src/importpositiondialog.cpp
- app/src/importpositiondialog.h
- core_lib/src/interface/editor.cpp
- core_lib/src/managers/viewmanager.h
"Tredje gang er lykkens gang" (Danish proverb)
I've made this extension to the much discussed import feature.
Here you can import relative to four positions, as shown in the screenshot below.
Whether my naming for the four possibilities are precise enough is up to you. Let's discuss it.
When importing to follow camera, we have to set the viewManagers importView for each image, which called for 4 lines of code in the Editor::importImage() function. If any of you know a smarter way, please tell me how.
Finally, this only addresses the urgent problem of the merged feature, that could be more precise. We should have a feature where we could import to whatever position we want. That must be another time.
> #1177 Added possibilities for import positions

- app/src/filedialogex.cpp
- app/src/filedialogex.h
- app/src/mainwindow2.cpp
- core_lib/src/util/fileformat.h
- core_lib/src/util/pencildef.h
This removes extensions from translations, only text that could be interpreted otherwise is translatable now.
I've also tweaked the strings.
This means that it's not up to the translator now to write the extension, thus we should see no more of those bugs where an extension is not added because of wrong format.
Should not be merged before #1262
> Remove extensions from translations and tweak some strings

- core_lib/src/managers/preferencemanager.cpp
One line of code that restores the saving of autosave settings in preferences
closes #1309
> 1309 restore autosave settings

- app/src/filedialogex.cpp
This is a quick fix for now, we should consider not opening the filedialog static, as there's no way to get the return codes this way... The save methods could also make use of Status instead for more error handling.
closes #1314
> #1314: Fix save dialog ignores if path is empty

- core_lib/src/managers/playbackmanager.cpp
- core_lib/src/soundplayer.cpp
This PR loads and keeps audio files in memory, and also fixes two small coding errors which were also causing audio delays. I am perhaps overly optimistic that this will completely fix #1179, #1227, #1298, and the many user complaints we've had everywhere else. This code still needs to be tested on Windows where the issue seems to be worst.
Assuming this works as I expect it to, the only remaining known issue with playback audio synchronization will occur when Pencil2D is not scrubbing at the target frame rate (either because it's set too high or the computer cannot process the frames fast enough).
> Fix playback audio sync issues

- core_lib/src/interface/timelinecells.cpp
- core_lib/src/interface/timelinecells.h
- core_lib/src/structure/layer.cpp
- core_lib/src/structure/layer.h
Includes:
+ current keyframe is highlighted with white
+ All layer keyframes are more visible
closes #1322
> Increase visibility of active layer keyframes

- core_lib/src/managers/layermanager.cpp
- core_lib/src/managers/layermanager.h
New layer is selected when created. Only tested on Win10, so it should work on all platforms ;-)
closes #1327
> New layer is selected after creation

- app/src/preferencesdialog.cpp
- core_lib/src/interface/scribblearea.cpp
- core_lib/src/interface/scribblearea.h
This PR updates the layer visibility in settings at all times.
In the Preferences, the slider and spinbox are disabled, when not in RELATIVE mode.
closes #1319
> LayerVisibility updated in settings. 

- app/src/displayoptionwidget.cpp
- app/src/displayoptionwidget.h
- app/src/toolbox.cpp
- app/src/toolbox.h
- app/ui/displayoption.ui
- app/ui/onionskin.ui
- core_lib/src/interface/basedockwidget.cpp
- core_lib/src/interface/basedockwidget.h
- core_lib/src/interface/flowlayout.cpp
This PR tweaks a few parts of the display and tools dock widgets' appearance. These include:
- Updating the minimum height of the widgets which use FlowLayout on resize so that they cannot be resized in such a way that hides tools or other items.
- Use FlowLayout instead of GridLayout for the display options widget
- Add support for horizontal centering to FlowLayout. I currently only have this enabled for the display widget as it looks a little weird to me when the tools are not left-aligned like in all other programs.
- Added a spacer to the bottom of the onion skins dock widget just so it behaves like the tool options widget
And here are some visuals
FlowLayout Resizing:
Horizontal centering:
Note that if you move a widget with FlowLayout from floating to a dock with a smaller width, …
> Layout tweaks

- app/src/mainwindow2.cpp
- core_lib/src/interface/editor.cpp
- core_lib/src/interface/editor.h
While working on the sound scrub feature, I accidentally found out, that the preference manager is not updated when the fps changes. The playback manager is updated, but the preference manager get the fps from the file that loads with Pencil2D, and is not updated until next time it is opened.
It has had no impact on Pencil2D, but it prevented me from an enhancement I wanted, and thus it was discovered.
> Preferencemanager updated when fps changes

- app/src/onionskinwidget.cpp
- The onion skin widget buttons that were bound to a shortcut weren't being updated by these shortcuts upon activation.
- It seems the updateUI method was missing the connection to the preference manager so this was added.
Thanks to CandyFace for the advice.
> Fix OnionSkinWidget Prev/Next Button Behavior

- app/app.pro
- core_lib/src/miniz.cpp
- tests/tests.pro
- util/after-build.ps1
Now that I've got a windows dev environment up and running I was able to reproduce those obscure compiler errors that @Jose-Moreno has been mentioning for a while.
The first part of the problem is that mingw does not use release and debug destination folder by default, so I've restructured the project file to use only that when it's msvc and none when it's g++
The second problem came from an earlier change we've made to the miniz library to fix some encoding issues.. that's good and all but it didn't compile with mingw64... so I looked online and found out that for g++, the ```<locale>``` header is needed. Please verify that it comples on both linux and windows still. I've tested it on my windows machine with MinGW but not MSVC.
> Fix MinGW windows compiling issues

- core_lib/src/interface/timeline.cpp
If you were in the middle of moving a selection and wanted to add a keyframe, the timeline didn't update properly.
Closes #1250
> 1250 Updating ui correct during transformation

- .travis.yml
- app/src/main.cpp
- util/after-build.sh
Took me long enough to figure out, but it’s finally here. To avoid insane amounts (~30MB) of bloat I had to pick the GStreamer plugins to distribute by hand, so there’s a chance I missed something, but I think most cases should be taken care of. Nonetheless, I think the most valuable “review” that can be done on this is trying it out on any nearby Linux systems. A build is available [here](https://drive.google.com/open?id=1h3JB80ZAv1ApcOQvzMqvu0E2UUkid1ng).
In addition to the sound stuff I also did some rework of the Travis setup, mostly by relocating the post-build instructions into a separate script (à la AppVeyor). The Doxygen packages I removed are required according to the deploy script, but personally I’m quite skeptical about that. The documentation certainly built fine without …
> Fix #1033 Broken sound playback in AppImages

- app/src/actioncommands.cpp
- app/src/actioncommands.h
- app/src/mainwindow2.cpp
- app/ui/mainwindow2.ui
Implemented as discussed. It is an action in the Help menu, and when clicked, it produces a warning message before opening the user directory. Works on Ubuntu, should be tested on other platforms.
> Add an action to open Pencil2D's temporary directory

- app/src/displayoptionwidget.cpp
- app/src/exportimagedialog.cpp
- app/src/exportmoviedialog.cpp
- app/src/importimageseqdialog.cpp
- app/src/mainwindow2.cpp
- app/src/onionskinwidget.cpp
- app/src/preferencesdialog.cpp
- app/src/presetdialog.cpp
- app/src/tooloptionwidget.cpp
- app/ui/mainwindow2.ui
- core_lib/src/graphics/bitmap/bitmapimage.cpp
- core_lib/src/graphics/vector/beziercurve.cpp
- core_lib/src/graphics/vector/vectorimage.cpp
- core_lib/src/graphics/vector/vectorimage.h
- core_lib/src/interface/scribblearea.cpp
- core_lib/src/interface/timecontrols.cpp
- core_lib/src/managers/playbackmanager.cpp
- core_lib/src/managers/selectionmanager.cpp
- core_lib/src/managers/viewmanager.cpp
- core_lib/src/movieexporter.cpp
- core_lib/src/movieexporter.h
- core_lib/src/movieimporter.cpp
- core_lib/src/structure/soundclip.cpp
- core_lib/src/structure/soundclip.h
- core_lib/src/tool/handtool.cpp
- core_lib/src/tool/movetool.cpp
- core_lib/src/util/mathutils.h
- core_lib/src/util/util.cpp
- core_lib/src/util/util.h
With the recent release of Qt 5.15, I once again had a closer look at my compiler output. Most of the changes are rather boring, but it’d be nice if someone could have a look at the copy assignment operators. I based them on existing, related code, but since I’m not exactly familiar with that part of the codebase I’m not really sure if that is sufficient.
Fixes #1370.
> Fix errors, warnings and deprecations from Qt 5.15

- core_lib/src/interface/editor.cpp
Pencil2D was crashing if there was no frame on frame 1, and you tried to Ctrl+A on that frame.
Checking for nullPtr fixes that.
Does this close #834?
> Checking for nullptr to prevent crash with Ctrl+A and Ctrl+D

- core_lib/src/canvaspainter.cpp
- core_lib/src/interface/editor.cpp
- core_lib/src/interface/scribblearea.cpp
- core_lib/src/structure/object.cpp
- core_lib/src/tool/buckettool.cpp
- core_lib/src/tool/erasertool.cpp
- core_lib/src/tool/movetool.cpp
- core_lib/src/tool/penciltool.cpp
- core_lib/src/tool/pentool.cpp
- core_lib/src/tool/polylinetool.cpp
- core_lib/src/tool/selecttool.cpp
- core_lib/src/tool/smudgetool.cpp
This is a follow up to #1371 and deals with the same type of issues that caused #834. Hopefully this takes care of all such issues.
> Fix more crashes when there is no previous frame

- core_lib/src/tool/penciltool.cpp
When drawing, the setting INVISIBLE_LINES was set, no matter what type layer was drawn onto.
Now it checks for Layer::VECTOR
> Check for vector layer, before toggle showInvisibleLines

- core_lib/src/graphics/vector/vectorimage.cpp
- core_lib/src/graphics/vector/vectorimage.h
- core_lib/src/tool/eyedroppertool.cpp
Eyedroppertool will:
Ignore invisible vector lines
Show the color of the top vector line (latest drawnline) when lines overlap
Prioritize the vector color (mCurves) over the mArea color when a vector is drawn over a bucketfill
> eyedroppertool improvements

- app/src/colorpalettewidget.cpp
This fixes a 'bug' that has often bothered me.
1) New colors were placed in front of the selected color, and that made sense before the colors could be dragged and dropped. I always expect to find the new colors at the bottom of the palette, because they logically should be appended to the palette. This PR places new colors at the bottom of the list.
2) The reason for having names for the colors is to use them. If we don't use the names, we might as well just have them numbered. My colors get names like 'Lisa skin', 'Lisa eyes', 'Lisa Hair' etc, and not 'Magenta', 'Vivid Reddish Purple', or some of the other suggested names. For that reason, I've put the rename color dialog up front, so you're naming your color when you add it. This is more logical, and if you indeed want the name to be …
> Position new palette colors at bottom, and renaming immediately

- app/src/importimageseqdialog.cpp
- app/src/importimageseqdialog.h
When importing files (arbitrary set, predefined set or gif animation), you could press OK without selecting any. This PR prevents that.
> Disabling OK until files are selected and verified

- core_lib/src/structure/object.cpp
This is a very small PR that is meant to update some of the colors (particularly the so called skin colors) from the default Pencil2D palette created in `object.h` and make it consistent with the nomenclature sampled from `colordictionary.h` when colors are automatically renamed.
> Make default color palette swatches nomenclature consistent

- .travis.yml
- pencil2d.pro
Address #1410 FreeBSD Qt resource tool doesn't work well with Unicode filenames
Add a qmake config flag `NO_TESTS` for package maintainers who don't want to run unit tests
Usage:
```
qmake pencil2d.pro CONFIG+=NO_TESTS
```
> qmake CONFIG+=NO_TESTS to skip building unit tests

- core_lib/src/interface/scribblearea.cpp
- core_lib/src/managers/viewmanager.cpp
- core_lib/src/managers/viewmanager.h
- core_lib/src/structure/camera.cpp
- core_lib/src/structure/camera.h
- core_lib/src/tool/handtool.cpp
- core_lib/src/tool/handtool.h
- translations/pencil_cs.ts
For zooming, Pencil2D currently handles all wheel events that are not pixel-based as if they had the same resolution. This leads to sub-par zooming for devices which report high resolution wheel data. With this PR, I fixed that by taking the same approach already used for pixel-based scrolling and tweaking it so that the algorithm satisfies a few additional properties:
- After first scrolling forward by X degrees, scrolling backward by the same X degrees returns the zoom to its original state
- Scrolling forward by X degrees, then scrolling forward by another Y degrees is the same as scrolling forward by (X + Y) degrees
- Using a mouse with "standard" 15 degree resolution, it’s possible to go back to exactly 100% from min/max zoom without having to use "Reset zoom/rotate"
- Using a mouse …
> Handle angle-based high resolution scrolling properly

- app/src/checkupdatesdialog.cpp
- app/src/checkupdatesdialog.h
- util/after-build.ps1
Addressing #1195
1. Now the version info request link is HTTPS (HTTP doesn't work anymore)
2. Deploy OpenSSL DLLs in our Windows CI process.
Note: 
The current Qt version (5.12) uses OpenSSL 1.1.1d
AppVeyor has OpenSSL pre-installed 
https://www.appveyor.com/docs/windows-images-software/
> Fix #1195 check for updates failure

- app/src/main.cpp
- app/src/mainwindow2.cpp
- app/src/mainwindow2.h
- app/src/pencilapplication.cpp
- app/src/pencilapplication.h
- core_lib/src/interface/scribblearea.cpp
This applies in particular to the eyedropper temporary tool, which is activated while switching to other applications with the alt+tab shortcut. The solution I have come up with for this problem is to catch the event that is generated when leaving an application and then reverting any temporary tool when that occurs.
This has only been tested on Linux, it should be tested on Windows as well to make sure that it generates the same event and fixes the issue.
> Fix temporary tools getting stuck if changing applications

- core_lib/src/structure/object.cpp
This is an alternative solution to the one provided in #1420. Fixes #1372.
> Only creating keyframes that exists in *.pclx: The Sequel

- app/src/mainwindow2.cpp
- app/src/mainwindow2.h
- core_lib/src/structure/filemanager.cpp
- core_lib/src/structure/filemanager.h
- core_lib/src/structure/layerbitmap.cpp
- core_lib/src/structure/object.cpp
- core_lib/src/structure/object.h
- core_lib/src/util/fileformat.cpp
- core_lib/src/util/fileformat.h
- tests/src/test_filemanager.cpp
Try to restore the last unsaved project, usually because of Pencil2D crashes.
A recovery popup will show if the app finds any project files left in the temp folder. 
There are two recovery modes:
1. Both `main.xml` and images (.png and .vec) are fine. In this case, just load the project up from the temp folder.
2. `main.xml` is broken. Then try to rebuild the main.xml based on the images left in `data` folder, and then call mode 1. In this mode, the images are no way to be on the correct position anymore.
Things need to do next but not included in this PR:
1. Preset pop-up. Both Recovery & Preset popup are showing when the app starts.
2. Inconsistency between images and main.xml. Maybe there are images in the data folder but images are not added to main.xml yet due to uncompleted save …
> Project recovery after Pencil2D crashes

- app/src/mainwindow2.cpp
After setting an additional attribute to the pegbar alignment dialog, the dialog closes properly, and with this change, I can't reproduce the crashes described by @Jose-Moreno .
This should fix #1428
> 1428 fix crash under peculiar circumstances

- app/src/actioncommands.cpp
- core_lib/src/managers/layermanager.cpp
A new sound layer was named 'Sound layer 2', even if one selected 'Sound layer'. The reason was that the nameSuggestLayer() function was called twice.
Fixes #1414
> New layer naming #1414

- app/ui/onionskin.ui
I recall seeing an issue about the new onion skin widget being too big and I agree that it is a problem, especially when working on a small monitor, so an immediate quick fix for the release could be to make it scrollable.
> Make onion skin widget scrollable

- core_lib/src/qminiz.cpp
- core_lib/src/util/util.h
The main changes here is that `mz_zip_reader_end` and `mz_zip_reader_end` are always called now, even if an error is encountered. When compressing always put `mz_zip_get_last_error` in the debug details if the compression fails. The remainder of the changes are cosmetic.
> Miniz improvements

- app/src/mainwindow2.cpp
- app/src/mainwindow2.h
The `Reset Windows` in Windows menu should reset all sub-panels to their default positions
> Fix #1437: "Reset Windows"

- app/ui/generalpage.ui
- core_lib/src/activeframepool.cpp
- core_lib/src/activeframepool.h
- core_lib/src/graphics/bitmap/bitmapimage.cpp
- core_lib/src/graphics/bitmap/bitmapimage.h
- core_lib/src/managers/preferencemanager.cpp
- core_lib/src/structure/keyframe.h
- core_lib/src/structure/object.cpp
- core_lib/src/structure/object.h
- core_lib/src/util/pencildef.h
- core_lib/src/util/util.cpp
- core_lib/src/util/util.h
`ActiveFramePool` can now manage the pool with a memory budget (for example 1GB) and calculate the actual total used memory by adding up the memory usage of each frame. This is a more accurate way to prevent the app crashing from out of memory.
Previously `ActiveFramePool` keeps a certain number of keyframes, for instance, 400 frames in the memory, which is not good due to the variation of the image size as well as memory usage.
The default pool size is 1GB.
> Manage ActiveFramePool using image size rather than number of frames

- core_lib/src/structure/filemanager.cpp
- core_lib/src/structure/filemanager.h
This is a PR of code refactoring. It's a preparation step for further file saving improvements.
There are 2 parts in this PR:
1. Breaking down `FileManager::save()` into 3 smaller functions 
- `flushKeyFrameFiles()`: write all bitmap/vector keyframes to the temp working folder.
- `writeMainXml()`: write the main xml to disk
- `writePalette`: write the palette xml to disk
This change makes the file save process more clear & descriptive, also make the second part possible.
2. Introducing `FileManager::flush()`
This function flushes all changes to the temp working folder without touching `.pclx`. Calling `flush()` at the right time will improve the recoverability of projects. For example, recovering a newly created project which has nothing in the temp working folder. More PRs will come …
> [Refactor] Break down FileManager::save() and introduce FileManager::flush()

- core_lib/src/interface/timelinecells.cpp
- core_lib/src/structure/layer.cpp
In order to make some progress on #550, I modified the timeline rendering to use colours from the application palette instead of hardcoded values. With this change, the only remaining dark theme issues are those related to the icons.
Here is a before/after comparison using a random dark theme:
In addition to the colour changes, I also simplified the design a little in order to accommodate the somewhat limited selection of colours available from QPalette and to make sure the timeline continues to look good regardless of which theme is used. I tested this with a wide range of different themes, both light and dark, and I’m happy with the results, but if you find a theme that “breaks” the timeline, let me know.
Grab a build here: [Linux](https://drive.google.com/file/d/1ykvkfqN0ikptV6fgY3hgK2B …
> Draw the timeline using palette colours (AKA dark theme support for the timeline)

- core_lib/src/interface/scribblearea.cpp
- core_lib/src/interface/scribblearea.h
- core_lib/src/tool/brushtool.cpp
- core_lib/src/tool/buckettool.cpp
- core_lib/src/tool/erasertool.cpp
- core_lib/src/tool/penciltool.cpp
- core_lib/src/tool/pentool.cpp
- core_lib/src/tool/smudgetool.cpp
- core_lib/src/tool/stroketool.cpp
- core_lib/src/tool/stroketool.h
- core_lib/src/util/pointerevent.cpp
- core_lib/src/util/pointerevent.h
The following issues have been identified as caused by #1443, and they are all hopefully resolved with these changes:
- Onion skins not updating when cached and a previous/next frame is changed
- Crash when scrubbing to large positions (exact cutoff where it starts to crash depends on the frame pool size)
- The workaround for the mouse move events produced by some tablets (i.e. the reed issue) broke the polyline tool and the cursor. I have changed the approach used to fix this issue, and hopefully everything is working alright now. This still needs to be tested to make sure it fixes the issue that @Jose-Moreno was having.
> Fix issues caused by #1443

- app/src/displayoptionwidget.cpp
- app/src/mainwindow2.cpp
- app/src/onionskinwidget.cpp
- app/src/toolbox.cpp
- app/ui/displayoption.ui
- app/ui/onionskin.ui
- app/ui/toolboxwidget.ui
- app/ui/tooloptions.ui
- core_lib/src/interface/timecontrols.cpp
- core_lib/src/interface/timeline.cpp
This PR tries to further address the onion skin widget as well as some other UI changes.
- The Onion Skin widget has been made a tad smaller
- Margins has been adjusted
- Min/max has been added next to the spinbox and the percentage sign has become a suffix of the spinboxes.
Both vertical and horizontal spacing should be cared for, even if the screen is much wider than it is tall, otherwise we'll just make the canvas area smaller, which I don't think is a good idea. I think we should keep the onion skin widget as is.
All widgets except the color inspector and colorwheel has been made scrollable, this makes it possible now to make the application quite small in height and should also fix most if not all problems with widget overflow, which we've seen in the wild.
The reason why I haven't …
> UI Widget layout

- app/src/mainwindow2.cpp
As title. Please see screenshots:
Go to `Windows` menu -> tick `Lock Windows`: Hide dock widget titlebar.
Untick `Lock Windows`: the title bar shows again
would love to know how it looks like on other platforms.
> Hide dock widget title bars when "Lock Windows" is selected

- core_lib/src/graphics/bitmap/bitmapimage.h
- core_lib/src/tool/eyedroppertool.cpp
- Eyedropper will now determine the color from anywhere within the pixel instead of only from the center of the pixel.
- Preview rectangle can now be seen on all backgrounds
- Preview color is now premultiplied, meaning the color represents the inspected pixel rather than the color multiplied with the background.
> Eyedropper improvements

- app/src/mainwindow2.cpp
- core_lib/src/interface/scribblearea.cpp
- core_lib/src/interface/scribblearea.h
fixes #1488 
To minimize painting bugs, we should keep all update within scribblearea, so that we can rely on updates always coming from inside, at least when it affects cache and the like.
> 1488 fix camera interpolation

- core_lib/src/interface/scribblearea.cpp
A pretty simple fix (once you figure out what’s going on), but I’d still prefer to have this reviewed because I’m not that familiar with the selection / move tool code.
> Fix extra movement when moving vector objects

- app/src/actioncommands.cpp
- app/src/actioncommands.h
- app/src/mainwindow2.cpp
- core_lib/src/interface/backupelement.h
- core_lib/src/interface/editor.cpp
- core_lib/src/movieexporter.cpp
This PR fixes multiple bugs related to importing and exporting audio. In particular it fixes:
- Different behavior between movie audio import and sound import (closes #1448, closes #1452)
- Exporting with empty sound frames causes the movie export to fail
- Fix empty sound keyframe being left when cancelling a sound import (closes #1449)
- Implement sound keyframe deletion undoing and fix empty keyframe being produced (note you may encounter #1557 when testing this, that has not been fixed and is unrelated)
- Fixed removing the wrong sound keyframe when importing a sound on an existing frame and cancelling
- Prevent empty keyframe from being created if a sound keyframe is removed and there are no other keyframes left on the layer
This should hopefully address all the issues some of our …
> Sound import/export bugfixes

- app/src/actioncommands.cpp
- app/src/mainwindow2.cpp
- app/src/pegbaralignmentdialog.cpp
- core_lib/src/interface/backupelement.cpp
- core_lib/src/interface/editor.cpp
- core_lib/src/interface/editor.h
- core_lib/src/interface/scribblearea.cpp
- core_lib/src/interface/scribblearea.h
- core_lib/src/interface/timeline.cpp
- core_lib/src/interface/timelinecells.cpp
- core_lib/src/managers/layermanager.h
- core_lib/src/managers/viewmanager.cpp
- core_lib/src/tool/brushtool.cpp
- core_lib/src/tool/buckettool.cpp
- core_lib/src/tool/erasertool.cpp
- core_lib/src/tool/penciltool.cpp
- core_lib/src/tool/pentool.cpp
- core_lib/src/tool/polylinetool.cpp
- core_lib/src/tool/selecttool.cpp
- core_lib/src/tool/smudgetool.cpp
- core_lib/src/tool/stroketool.cpp
Although we were about to have the frame update situation under somewhat control, I found many cases where the entire cache doesn't have to be invalidated, thus I've added more signals and methods to the appropriate situations where we require more control of the cache. Furthermore I found a bug where if our current frame cache is relevant, we still don't paint the rendering stack properly, eg. missing onion skin.
All cache control is now placed privately inside ScribbleArea and only through the appropriate slots, will the cache be updated. UpdateFrame and updateCurrentFrame will call update() and only invalidate frame cache when a frame is modified.
Frame cache invalidation will happen mostly automatically through all tools via ScribbleArea::setModified() which invalidates the current …
> Rework frame updating

- core_lib/src/interface/editor.cpp
- core_lib/src/interface/scribblearea.cpp
- core_lib/src/interface/scribblearea.h
Addressed a couple of issues found in #1562
There is still an issue and I haven't figured out how to fix. The **Show Onion Skins during Playback** checkbox doesn't work because the frame cache already has onion skins baked in. There is probably no easy fix at the moment due to the `CanvasPainter` implementation. Please let me know if you have any idea.
> Cache fixes for #1562

- app/src/actioncommands.cpp
- app/src/mainwindow2.cpp
- core_lib/src/interface/editor.h
- core_lib/src/interface/scribblearea.cpp
- core_lib/src/interface/scribblearea.h
- core_lib/src/interface/timelinecells.cpp
- core_lib/src/structure/layer.h
When calling frameModified, the onion skin cache not would be updated, meaning the cache for the skinned frames would be invalid and cause the familiar residue effect...
Way to reproduce:
1. Add 2 frames or move while onion skin is enabled
2. move scrubber to the first frame you added
3. Draw on the frame
4. Now scrub to the last added frame and paint on it
result: notice the residue effect due to the onion skin cache not having been updated.
This PR fixes that problem by making sure the onion skin cache is updated when the current frame is modified.
> Fix cache rendering issue with onion skin

- app/src/colorslider.cpp
error message: EndDraw failed: 0x88990014
Some widgets show just blank with black color.
> fix ui rendering issue when using direct2d platform on windows. (-platform direct2d)

- app/src/mainwindow2.cpp
- app/src/mainwindow2.h
- app/src/pegbaralignmentdialog.cpp
- app/src/pegbaralignmentdialog.h
- app/src/toolbox.cpp
- app/src/toolbox.h
- app/ui/pegbaralignmentdialog.ui
- core_lib/core_lib.pro
- core_lib/src/graphics/bitmap/bitmapimage.cpp
- core_lib/src/graphics/bitmap/bitmapimage.h
- core_lib/src/interface/editor.cpp
- core_lib/src/interface/editor.h
- core_lib/src/structure/pegbaraligner.cpp
- core_lib/src/structure/pegbaraligner.h
- core_lib/src/util/pencilerror.cpp
- core_lib/src/util/pencilerror.h
The PR is focused on moving pegbar related code into its own core class but it contains a bunch of improvements and fixes too.
Among the list of changes:
- Fix cache issue caused by not calling frameModified.
- PegStatus now inherits from Status to make use of existing functionality.
- Implemented the ability to update a status object while keeping data.
- Wording
Quality of life improvements:
- "Select" tool will be set upon opening the dialog
- A selection will be made unless one already exists
- First layer will be pre-selected
Other:
- Make sure dialogs are being closed when starting a new project context.
Cleanup code...
> Pegbar refactoring and fixes

- app/src/onionskinwidget.cpp
- app/ui/onionskin.ui
These are some small modifications to the onion skin panel with the primary goal of decreasing the minimum width of the panel, and cleaning up the underlying structure a bit. Summary of changes:
- Use QGroupBox to group together items in the panel. This is what this widget was intended for, but it does come with some subtle aesthetic changes that we will have to agree on.
- Remove unnecessary elements. There were some useless horizontal spacers, and a layout item which could be set as the layout of a QWidget object instead.
- Use a combination of the FlowLayout and HBoxLayouts for the distributed opacity section. Currently this is the widest section, and this allows the items to be arranged vertically only if there is not enough horizontal space.
- Remove the fixed minimum size constraint …
> Onion skin panel touchups

- core_lib/src/interface/editor.cpp
- core_lib/src/interface/editor.h
Add boolean return value on backup function so that we can check if the backup was *actually* successful.
Fixes #1557
> Fix keyframe undo that would cause crash or double undo in some cases (issue #1557)

- core_lib/src/interface/scribblearea.cpp
Fix cache issue caused by onFrameModified not being called when drawing on previous keyframe, making the latest stroke invisible upon release event.
closes #1576
> Fix cache bug when drawing on previous keyframe

- core_lib/src/interface/scribblearea.cpp
Removes call to `HandTool::pointerReleaseEvent`, which would call `ScribbleArea::setPrevTool`, which would call `ToolManager::setCurrentTool` where it would set the previously used tool, but the `HandTool::pointerReleaseEvent` would go on, causing an icon-function mismatch.
Fixes #1198
> Prevent stuck cursor icon when transitioning from MMB to RMB

- .github/actions/install-dependencies/install-dependencies.sh
- .github/actions/setup-environment/setup-environment.sh
- .github/workflows/ci.yml
- app/src/checkupdatesdialog.cpp
[Time to ditch Trusty, it seems!](https://github.com/probonopd/linuxdeployqt/commit/58cbda4aeab0d71b859be59a3eef59df2dd415c6) The code changes in this PR aren’t that interesting, the main focus for review should be testing [the build](https://drive.google.com/file/d/1VtA0n4GEFSVVSodQIFhCT5chveHervtm/view) and making sure all those different dependency versions don‘t cause any regressions (especially for multimedia, since I switched from an unofficial PPA to Ubuntu’s official repositories there). Personally, I haven’t found any issues during my brief test, in fact it confirmed my suspicion that a newer Qt version would finally fix #1017 for good. With any luck, it might also fix some of the other Linux issues such as #1032 which we’ve never been able to reproduce. Still, I think it would …
> Upgrade Linux builds to Xenial and Qt 5.15

- core_lib/src/graphics/bitmap/bitmapimage.cpp
- core_lib/src/interface/editor.cpp
- core_lib/src/interface/scribblearea.cpp
- core_lib/src/tool/movetool.cpp
This PR contains small fixes for two issues:
1. Transparent areas turning black when transformed (#1641)
2. The view does not update after cancelling a selection with the escape shortcut.
> Selection transformation fixes

- .github/workflows/ci.yml
As long as we don’t do anything in the tests that actually requires window system integration, this should be enough to make the tests run on CI. Otherwise we’ll need to run an actual display server for the Linux tests, which seems like something of a hassle.
> Run tests without window system integration

- .github/workflows/ci.yml
Should hopefully fix the failing PR builds. Let’s see if this works.
> Upload nightly builds only if key is available

- app/src/statusbar.cpp
- core_lib/src/interface/scribblearea.cpp
- core_lib/src/interface/scribblearea.h
- core_lib/src/managers/toolmanager.cpp
- core_lib/src/managers/toolmanager.h
- core_lib/src/tool/handtool.cpp
- core_lib/src/tool/polylinetool.cpp
- core_lib/src/tool/polylinetool.h
- core_lib/src/tool/selecttool.cpp
- core_lib/src/tool/smudgetool.cpp
- core_lib/src/tool/stroketool.cpp
- core_lib/src/tool/stroketool.h
This moves all the handling of temporary tools out of ScribbleArea and into ToolManager. There are also changes to the implementation and behavior that will make it more verstatile and able to handle weird corner cases better (ex. shortcuts while using temporary tools). There's too many changes to how the temporary tools work to list them all, but here is a list of the bigger changes that I can think of off the top of my head:
- Shortcuts work with temporary tools now. If you say used the right click to use the hand tool temporarily, then you could hold control and it would zoom just as holding control with the hand tool normally does.
- You cannot have nested temporary tools. The first temporary tool activated takes precedence and prevents any further temporary tools from being activated …
> Rewrite temporary tool handling

- core_lib/src/interface/scribblearea.cpp
- core_lib/src/interface/scribblearea.h
- core_lib/src/overlaypainter.cpp
This will make anything painted on the canvas pixmap much crisper, on high resolutions screens.
The change will be noticeable as soon as we begin to draw more elements eg. (the work done in #1587), it might also improve the overall image quality of the drawings on said screens.
> Implement device pixel ratio for canvas

- core_lib/src/structure/layercamera.cpp
Realized that since the camera is born with a EasingType, there was no need to add it, so the two lines of code, that made the software crash under certain circumstances, have been deleted.
The function containing the two lines of code is heavily improved in a PR #1587, and this PR is hopefully merged into the master branch soon, so just deleting the two lines of code if sufficient now, in my opinion.
Solves #1684
> Removed two lines of code that made the software crash #1684

- core_lib/src/qminiz.cpp
- core_lib/src/qminiz.h
- core_lib/src/structure/filemanager.cpp
This includes a special "mimetype" file at the beginning of the zip archive of pclx files containing the mime type used for pclx files. Many common zip-based file formats (epub, openraster, openoffice, krita, and more) use this specific approach to help distinguish their files from other zip files. This provides a unique file signature for pclx projects and allows them to be identified by other programs such as the "file" utility on linux, and possibly file association on other platforms as well. This should not impact the reading of project files in any way since the file is outside the data directory and in fact won't even appear in the temporary directory.
> Add mimetype to pclx files

- app/src/actioncommands.cpp
- app/src/actioncommands.h
- app/src/mainwindow2.cpp
- core_lib/src/interface/timeline.cpp
- core_lib/src/interface/timeline.h
- core_lib/src/managers/layermanager.cpp
- core_lib/src/managers/layermanager.h
I made a small PR that can duplicate Bitmap and Vector layers. I've only tested it on bitmap layers, but the code should work with both.
I can't find any reason to duplicate camera or sound layers, so until anyone can see a use-case for that, it is only artwork layers.
Solves #498
> Duplicate layer function added to layer buttons. 

- core_lib/src/qminiz.cpp
- core_lib/src/qminiz.h
- core_lib/src/structure/filemanager.cpp
- core_lib/src/structure/filemanager.h
- core_lib/src/util/fileformat.h
- core_lib/src/util/pencilerror.h
This PR makes a few changes to the filemanager, improving the error handling and fixing a few situations where the project could be corrupted and a backup wouldn't be made.
> Filemanager improved error handling

- app/src/main.cpp
- app/src/pencil2d.cpp
- app/src/pencil2d.h
On startup this will check if there is another instance of Pencil2D already running. If there is, the user will be warned of the issues that can arise from running multiple instances of Pencil2D simultaneously (as a result of the shared temporary folder directory and shared preferences file).
This check is done by creating a lock file and lock it on startup. If the locking fails, the warning is shown. If Pencil2D crashes, the lock file will remain and will be stale, however Qt has some checks under the hood that will check for running processes and match the process id and name so that in this case, the next instance of Pencil2D will still be able to successfully acquire the lock and no warning will be produced.
> Check for multiple application instances

- app/src/main.cpp
- app/src/mainwindow2.cpp
- app/src/mainwindow2.h
- app/src/pencil2d.cpp
- core_lib/src/structure/filemanager.cpp
- core_lib/src/structure/filemanager.h
- core_lib/src/structure/layer.cpp
- core_lib/src/structure/layerbitmap.cpp
- core_lib/src/structure/layercamera.cpp
- core_lib/src/structure/layersound.cpp
- core_lib/src/structure/layervector.cpp
- core_lib/src/structure/object.cpp
- core_lib/src/structure/object.h
This PR is a collection of various unrelated fixes and enhancements. I don’t think any of them have been (formally) reported. Here’s a list of the issues:
- An issue where the project recovery dialog was not modal, which caused it to appear behind the main window on my system
- Some runtime warnings about missing object names for the toolbars. This didn’t seem to cause any actual issues, but I figured I should fix it anyway
- An issue that caused the undo/redo shortcuts not to work under certain circumstances, for example right after program startup
- An issue where the translation context was set incorrectly for some strings due to inappropriate use of QObject::tr()
- An issue where Pencil2D ignored even the --help and --version options in release builds when another instance was already …
> Assorted fixes

- app/src/actioncommands.cpp
- app/src/actioncommands.h
- core_lib/src/managers/soundmanager.cpp
- core_lib/src/managers/soundmanager.h
- core_lib/src/movieexporter.h
Currently Pencil2D can't export animations with >= 63 frames due to limitations with the ffmpeg filter inputs. This warns the user when they've added too many sound clips, and produces a more specific error when attempting to export an animation with too many sound clips.
This could be improved, but I think it's good enough for a temporary solution. I have a movie exporter rewrite partially finished which I would like to complete before making changes to the ffmpeg command to allow for any number of sound clips to be exported. This could be a while out though, so I think this is a reasonable solution in the mean time.
> Sound clip count warning

- core_lib/src/graphics/bitmap/bitmapimage.cpp
- core_lib/src/managers/clipboardmanager.cpp
- core_lib/src/structure/layercamera.cpp
- tests/src/test_bitmapbucket.cpp
This PR fixes the three issues Jose reported recently:
- Fixes #1726 by reading from the system clipboard only when its contents were written by other applications
- Fixes #1727 by simply removing two noop lines
- Fixes #1728 by ensuring that BitmapImage always uses the premultiplied ARGB32 format. There was already an “on-demand” conversion that scribble added a while back but I figured it’d be a good idea to prevent BitmapImage from ever using unintended formats to begin with. That should also take care of any other potential issues in that area, like Jose suggested in the report.
> Fix recently reported issues

- core_lib/src/soundplayer.cpp
I had another look at the sound layer deletion crash and I think I finally did figure how to fix it – or work around it, rather. Looks like it’s a bug in the DirectShow backend of Qt Multimedia that results in a segfault when it is destroyed while paused. Neither the GStreamer backend nor the Windows Media Foundation backend exhibit this behaviour. Fortunately, it’s pretty easy to work around.
> Fix crash when deleting sound layer after scrubbing

- app/src/actioncommands.cpp
- core_lib/src/movieimporter.cpp
I took a look at the truncated audio issue for certain file formats and figured out how to fix it – or work around it, rather. Once again, it’s an issue that is specific to the DirectShow multimedia backend on Windows. This backend seems to have trouble properly playing WAV files containing certain metadata that FFmpeg includes. I actually looked at the files in a hex editor and the format of the metadata looks completely fine, so FFmpeg doesn’t do anything wrong here AFAICT. I also tried both the GStreamer backend and the Windows Media Foundation backend and both of those worked fine. It’s really just the DirectShow backend that doesn’t work properly. As a workaround I simply added some FFmpeg options to strip all metadata. Because users could conceivably import problematic WAV files …
> Fix truncated playback for converted audio clips on Windows

- app/src/actioncommands.cpp
- core_lib/src/structure/layer.cpp
- core_lib/src/structure/layer.h
- core_lib/src/structure/layerbitmap.cpp
- core_lib/src/structure/layercamera.h
As reported by Nelphy [on Discord](https://discord.com/channels/342369662710972417/395346048727515137/1074501500103036988). I also thought about renaming loadKey()… fundamentally, it’s more general-purpose than what we’re using it for so far IMO.
In the future, I think we should reconsider how we enforce the “min. one keyframe per layer” requirement. It’s a bit inconsistent right now with different assumptions made in different places, which is fundamentally what led to this issue.
> Fix emtpy frame on position 1 when duplicating layer

- core_lib/src/interface/editor.cpp
Stumbled across this bug purely by chance. Seems to be another issue I missed while reviewing #1724. Steps to reproduce:
1. Create a vector layer (or switch to an existing one)
2. Go to any frame that does not have a keyframe on that vector layer
3. Switch to any other layer → Segfault
> Fix crash when switching away from vector layer while not on a keyframe

- app/src/importimageseqdialog.cpp
- app/src/mainwindow2.cpp
- core_lib/src/interface/editor.cpp
- core_lib/src/interface/editor.h
- translations/pencil_cs.ts
Fixes #1674
I am new to contributing to Pencil2D and would really appreciate any feedback on these fixes, especially the debugging and error messages. Thank you!
> More detailed error reporting for image import failure

- core_lib/src/movieimporter.cpp
The -bitexact option was only added in FFmpeg 4 and is not available in older versions. Luckily, it is no more than a convenient shortcut for the bitexact codec and format flags, which should be old enough.
> Replace -bitexact FFmpeg option with more compatible -(f)flags

- core_lib/src/movieexporter.cpp
Feature or bug... you decide 😄 
https://discuss.pencil2d.org/t/how-to-mute-one-track-when-exporting/7182/4
> Ignore hidden sound layers when exporting video

- core_lib/src/movieexporter.cpp
In versions of ffmpeg < 3.2, passing a single audio track to the amerge filter is not allowed. This simply skips the amerge step when there is only one audio clip.
This was causing issues for exporting projects with a single audio clip in the Linux AppImage nightly builds where an older version of ffmpeg is currently being bundled.
> Don't use amerge when exporting a single audio clip

- app/src/actioncommands.cpp
- core_lib/src/managers/viewmanager.cpp
- core_lib/src/managers/viewmanager.h
- core_lib/src/tool/handtool.cpp
Fixes #1777.
_Please note that I am not an experienced C++ developer, so please let me know if something can be improved!_
This PR adds a check to `ActionCommands::rotateClockwise()`, `ActionCommands::rotateCounterClockwise()` and `HandTool::transformView()` that inverts the rotation direction if the view is flipped either horizontally or vertically (but not both), so it's more intuitive:
Shortcuts (Z then R):
https://github.com/pencil2d/pencil/assets/75134774/ac722475-312d-4ac9-aeee-42c81653dcd6
Hand Tool:
https://github.com/pencil2d/pencil/assets/75134774/5e6d216b-31dd-4e88-844d-06c87b3a86c9
> Invert canvas rotation direction if view is flipped

- .github/actions/create-package/create-package.sh
- .github/actions/install-dependencies/action.yml
This switches from the (now unavailable) OpenSSL builds provided by Qt to those provided by FireDaemon. For more info on those builds see [here](https://kb.firedaemon.com/support/solutions/articles/4000121705). These builds seem to be the best option right now, others are either the wrong version (1.0 or 3.x), are not up-to-date or do not provide 32-bit binaries.
> Fix OpenSSL build failure

- app/src/bucketoptionswidget.cpp
- app/src/bucketoptionswidget.h
- app/src/tooloptionwidget.cpp
- app/ui/bucketoptionswidget.ui
- core_lib/src/graphics/bitmap/bitmapbucket.cpp
- core_lib/src/graphics/bitmap/bitmapbucket.h
- core_lib/src/managers/toolmanager.cpp
- core_lib/src/managers/toolmanager.h
- core_lib/src/tool/basetool.cpp
- core_lib/src/tool/basetool.h
- core_lib/src/tool/buckettool.cpp
- core_lib/src/tool/buckettool.h
- core_lib/src/util/pencildef.h
- tests/src/test_bitmapbucket.cpp
Fixes #1735 as well as another unreported bug.
This PR also removes the Fill to layer feature as i've come to the conclusion that its usecase is too specific, while also discovering bugs that would complicate the code further, in order to fix.
> Buckettool fill bugs

- core_lib/src/canvaspainter.cpp
- core_lib/src/canvaspainter.h
- core_lib/src/interface/scribblearea.cpp
- core_lib/src/interface/scribblearea.h
- core_lib/src/overlaypainter.cpp
- core_lib/src/overlaypainter.h
- core_lib/src/util/util.cpp
- core_lib/src/util/util.h
- tests/tests.pro
This approach uses its own line clipping implementation since Qt doesn’t seem to provide any functionality for this sort of use case.
> Fix perspective overlays not always covering the entire view

- app/src/actioncommands.cpp
- app/src/actioncommands.h
- app/src/doubleprogressdialog.cpp
- app/src/doubleprogressdialog.h
- app/src/filedialog.cpp
- app/src/importimageseqdialog.cpp
- app/src/mainwindow2.cpp
- app/src/mainwindow2.h
- app/ui/exportimageoptions.ui
- app/ui/mainwindow2.ui
- core_lib/src/interface/editor.cpp
- core_lib/src/interface/editor.h
- core_lib/src/structure/object.cpp
- core_lib/src/util/fileformat.cpp
- core_lib/src/util/fileformat.h
- core_lib/src/util/filetype.h
This PR contains a few loosely related changes to image importing. Specifically:
- Add support for importing animated WebP images (same Qt code that handles animated GIF import)
- Progress dialog for animated image import with abort support
- Separate logic handling single and animated image importing
- Make movie export modal so the user can't perform other operations that might interfere with the export ([report](https://discuss.pencil2d.org/t/accidentally-using-a-drawing-tool-on-a-bitmapped-layer-whilst-pencil2d-is-expecting-an-mp4-video-file/7599?u=j5lx))
- Fix possible issue with error checking during image importing. I did not try to produce the issue, but based on the code it would probably handle some image corruption errors incorrectly.
- Add non-animated WebP image import/export
> Improve support for animated image importing

- core_lib/src/canvaspainter.cpp
This PR fixes a small cosmetic bug I stumbled upon while working on the new undo/redo feature.
How to reproduce:
1. Draw a vector stroke
2. Select it using the Select tool
3. Move or transform using the Move tool
4. undo/redo the operation and notice that it might either glitch and show the previous state then the new state, or it might not show the new state until you stop holding down ctrl or cmd on mac.
I also simplified the rendering logic a bit, check the commits for clarification about what does what.
> Fix delayed vector transformation rendering

- app/src/timelinecells.cpp
- core_lib/src/interface/editor.cpp
- core_lib/src/interface/editor.h
- core_lib/src/structure/layer.cpp
- core_lib/src/structure/layer.h
- core_lib/src/util/pencilerror.cpp
- core_lib/src/util/pencilerror.h
This fixes the crash reported at <https://discuss.pencil2d.org/t/pencil2d-crashes-when-i-import-an-image-to-a-hidden-layer/8016?u=j5lx>.
- Also fixed a potential memory leak in Layer::addNewKeyFrameAt
- Also disabled timeline hover effect for hidden layers since double-click-to-add-keyframe is disabled for those
- Also implicitly fixed an issue where trying to import to hidden layers showed a warning for empty frames but not on keyframes
> Fix crash when importing image to empty frame on hidden layer

- core_lib/src/tool/polylinetool.cpp
First reported here: https://discuss.pencil2d.org/t/problems-with-nightly-build-11-april-2024/8025
On the bitmap layer, applying a polyline path results in ScribbleArea::paintBitmapBuffer being called, which clears the mTiledBuffer. However, this function is never called when using the tool on the vector layer where the the curve is added by the tool. It will also never get cleared if clearToolData is called directly, but it seems that this function isn't currently being called outside the polyline tool. I've refactored it a bit so when clearToolData is called, the buffer is always cleared (and always after deactivating the tool so ScribbleArea::updateFrame works). One slight change is that isActiveChanged will only be triggered if mPoints is not empty, which makes sense because if it is …
> Fix polyline buffer not always being cleared

- .github/actions/create-package/create-package.sh
- .gitignore
The use of `macdeployqtfix` is no longer needed as the official Qt deployment tool `macdeployqt` works as expected.
I carefully checked the Mac app bundles before and after applying `macdeployqtfix`, and I didn't see any differences between the two. Therefore, it should be safe to remove `macdeployqtfix` from our deployment process.
The only scenario where `macdeployqtfix` may be required is building the legacy Mac version, which is built with Qt 5.6 as far as I know.
> Remove "macdeployqtfix" from our deployment script

- .github/workflows/ci.yml
- util/common.pri
Also cleans up other compiler options a bit:
- use strict_c/c++ QMake feature to disable compiler extensions instead of messing directly with compiler flags
- same with msvc_mp and utf8_source. the latter also does compiler detection so there should be no need for special handling of legacy builds
- -stdlib=libc++ for macOS is removed since it appears to be the default since Qt 5.1
- QMAKE_LINK{,_SHLIB} = $$QMAKE_CXX also appears to be the default
> Enable C++17 by default when building against Qt 6

- core_lib/src/graphics/bitmap/tiledbuffer.cpp
- core_lib/src/graphics/bitmap/tiledbuffer.h
When drawing with the Pen tool with the width set to 1.00 (and also at lower and slightly higher sizes) and antialiasing turned off, there would occasionally be gaps in the stroke. I've determined that this is to be expected when the point being drawn with a specific area. Consider this diagram:
The black grid represents the edges of four pixels. The light blue represents the center and radius of the circle to be drawn for a tool with a width (ie. diameter) of 1px. The dark blue dots represent the center of the pixels. As best as I can figure, when QPainter::drawEllipse is called without antialiasing, it will only fill in the pixels where the center of those pixels are contained within the ellipse. As you can see in this example, none of the pixels meet this criteria, so nothing would be …
> Fix gaps when drawing with small pen and antialiasing off

- app/src/generalpage.cpp
When changing languages in the preferences window, this displays the warning in the target language instead of the current language so that people can actually read and understand it.
> Warn that translation changes require restart in new language

- app/src/exportmoviedialog.cpp
- app/src/exportmoviedialog.h
- app/src/importexportdialog.cpp
- app/src/importexportdialog.h
- app/ui/exportmovieoptions.ui
Fixes #1491. Has some small layout jumps when the warning is shown or hidden that I’m not quite sure how to properly deal with, but that’s still much better than the confusing wall of text that we have now.
> Prevent MP4 export with invalid resolution

- .github/actions/create-package/create-package.sh
- .github/workflows/ci.yml
We do this for now by introducing more mac os runners. This means that we deploy proper arm64 builds now as well as x86_64.
Ideally we would build universal binaries but Homebrew does not support building cross platform, as such we would have to build Qt ourselves in order to support this.
Note: We have to remember to make changes to the website, so we can see both new build types
> Fix build server only deploys arm64 macOS binaries

- .github/actions/create-package/create-package.sh
- .github/actions/install-dependencies/install-dependencies.sh
- docs/installer-development.md
- util/installer/pencil2d.bundle.wxs
- util/installer/pencil2d.cpp
- util/installer/pencil2d.pro
- util/installer/pencil2d.thm
This updates the installer from WiX 4 to WiX 5, which came out earlier this month. WiX 5 moved the bootstrapper application (think of it as the UI) out-of-process, so the changes are a bit more extensive than usual but still pretty straightforward. Some packages and header files got renamed, initialisation moved to OnCreate and localisation loading moved to OnThemeLoaded. The window icon is made explicit since it is now created in a separate process and therefore no longer inherited from the main installer binary.
Additionally, I also added a small workaround for a WiX caching issue, which is unrelated to the version 5 update.
Already tested a bunch of different scenarios and haven’t seen any new issues pop up so far.
> Update to WiX 5

- app/data/org.pencil2d.Pencil2D.metainfo.xml
Resolves #1812. Here’s what the brand colours look like in their preview tool (still using the current, outdated screenshot):
For examples of other apps, check out [the Flathub home page](https://flathub.org/).
I’m a bit unsure about the dark brand colour. When you make it too light, the contrast against the circle isn’t that good, but when you make it too dark, the contrast against the tip of the pencil suffers. Would appreciate some feedback there. You can try out the preview tool at https://docs.flathub.org/banner-preview/ if you’d like to experiment some yourself. AppStream does not allow specifying separate icons for light and dark mode.
> Update AppStream summary and add brand colors

- core_lib/src/structure/filemanager.cpp
- core_lib/src/structure/layerbitmap.cpp
- core_lib/src/structure/layersound.cpp
- core_lib/src/structure/layervector.cpp
- core_lib/src/util/util.cpp
- core_lib/src/util/util.h
- tests/src/test_layerbitmap.cpp
- tests/src/test_layersound.cpp
- tests/src/test_layervector.cpp
- tests/tests.pro
This PR adds additional checks to the loading of bitmap/vector/sound layers so that they will not be loaded if they are outside of the data directory. This can occur with specially crafted main.xml files, or with symlinks. This closes multiple admittedly unlikely security threats in the program that can result in exfiltrating images from arbitrary locations though animations, and even duplicating arbitrary files under some circumstances. Tests have also been written for the scenarios this PR covers with the exception of symlinks (and possibly Windows shortcuts) because Qt has very bad support for symlink creation.
This also incidentally fixes an issue where an infinite loop will occur when loading a main.xml file that contains a non-element node (ex. an xml comment) in the sound layer.
> Prevent Pencil2D projects from referencing external files

- app/src/preferencesdialog.cpp
- app/ui/generalpage.ui
- app/ui/preferencesdialog.ui
Fixes #1850 by simply removing the size restriction altogether. I couldn’t think of a good reason to keep it. I also made the dialog a little bigger by default and made some changes to the “tab bar” to avoid cutting off long translations.
Before:
After:
> Improve preferences layout for long translations

- app/src/layeropacitydialog.cpp
- app/src/layeropacitydialog.h
- app/src/timelinecells.cpp
- app/ui/layeropacitydialog.ui
Things I bumped into while writing release notes for 0.7.0, although I only found one thing I think is pretty fundamental, which is the fading mechanism that doesn't fade entirely. The rest are things that can be worked around.
if possible it would be nice to have them fixed before the release, since i'm hoping to mention the feature in our release post.
Fixes #1855
> Fix fade in/out not working properly.

- app/src/timelinecells.cpp
Based on the message from the Software's discord server, quoted:
> Not sure if it's been discussed here but:
First, double clicking in anywhere in the timeline gives you a new keyframe. Double clicking on a keyframe appends one after it.
When you need to move a keyframe, you need to click on it first before you can drag it around. If I happen to do this too fast, pencil2d registers this as a double click and does the keyframe appending. This can be annoying 
> I think it'll help a lot if pencil2d distinguishes between double clicking on an empty space and on a keyframe
This PR does exactly what the message above wants to. When double clicking on an existing keyframe, the program won't make a new keyframe, instead only selects it. Beneficial for those who want to drag the keyframe around …
> Do not make a new keyframe if double clicking on an existing keyframe

- core_lib/src/canvascursorpainter.cpp
When rotating the canvas, the brush cursor displays the wrong size. This was because mapRect is used, which will expand the size of a QRect to fit the bounding box of a rotated rectangle. This fix manually applies the view transform to the rect by translating the rect (based on the view translation, scale and rotation) and scaling the rect size without actually rotating the rect.
Fixes #1868.
> Fix brush cursor size with canvas rotation

- app/src/importimageseqdialog.cpp
- app/src/repositionframesdialog.cpp
- core_lib/src/interface/backupelement.cpp
- core_lib/src/interface/editor.cpp
- core_lib/src/interface/scribblearea.cpp
- core_lib/src/managers/layermanager.cpp
- core_lib/src/movieexporter.cpp
- core_lib/src/structure/filemanager.cpp
- core_lib/src/structure/pegbaraligner.cpp
- core_lib/src/tool/cameratool.cpp
- core_lib/src/tool/cameratool.h
- core_lib/src/tool/movetool.cpp
- core_lib/src/tool/smudgetool.cpp
This PR fixes a handful of simple warnings, mostly missing `emit` keywords and unused QStrings.
There were a lot more warnings but unfortunately my Qt and C++ knowledge isn't good enough to handle those so I decided not to risk breaking something. At least I fixed more than just the missing `emit`s.
> Fixed a few warnings

- core_lib/src/managers/toolmanager.cpp
- core_lib/src/managers/toolmanager.h
- core_lib/src/tool/basetool.cpp
- core_lib/src/tool/basetool.h
- core_lib/src/tool/stroketool.cpp
- core_lib/src/tool/stroketool.h
During Quick Sizing, Pencil2d tries to write changes to disk every time the width/feather changes. Some devices, particularly drawing tablets, send events at a high rate, causing Pencil2d to fail to keep up with with the events and hang for a moment.
This PR temporarily fixes the issue by introducing new methods that only changes the properties, then calling the original methods (which includes writing to disk) once we're done doing Quick Sizing.
> Temporarily modify width and feather during Quick Sizing

- app/src/errordialog.cpp
- app/src/errordialog.h
- app/src/mainwindow2.cpp
- app/ui/errordialog.ui
- core_lib/src/graphics/bitmap/bitmapimage.cpp
- core_lib/src/graphics/vector/vectorimage.cpp
- core_lib/src/managers/undoredomanager.cpp
- core_lib/src/qminiz.cpp
- core_lib/src/soundplayer.cpp
- core_lib/src/structure/filemanager.cpp
- core_lib/src/structure/layer.cpp
- core_lib/src/structure/layerbitmap.cpp
- core_lib/src/structure/layersound.cpp
- core_lib/src/structure/layervector.cpp
- core_lib/src/structure/object.cpp
- core_lib/src/util/pencilerror.cpp
The purpose of this PR has been to make the error report cover more steps, introduce "Error" to make it more explicit what's a information, a warning and an error.
I've also tried to make it fail faster rather than spitting out all kinds of irrelevant information when the actual error happened 4 lines above.
Here's an example of what our current report looks like:
```
Raw file path: /Users/mrstevns/Desktop/p2d testing/test-save-corruption.pclx
Resolved file path: /Users/mrstevns/Desktop/p2d testing/test-save-corruption.pclx
File name: /Users/mrstevns/Desktop/p2d testing/test-save-corruption.pclx
Recognized New zipped Pencil2D File Format (*.pclx) !
Miniz found an error while reading the file. - 7, failed finding central directory
Miniz found an error while closing file file. - 24, invalid …
```
> Add more details to FileManager error report

- ChangeLog.md
- app/src/mainwindow2.cpp
- app/src/shortcutspage.cpp
- app/ui/mainwindow2.ui
- core_lib/data/resources/kb.ini
- core_lib/src/tool/polylinetool.cpp
- core_lib/src/tool/polylinetool.h
- core_lib/src/util/pencildef.h
#1861 Introduced the ability to delete segments of an active polyline with a shortcut (the backspace key by default). This prevented the keypress event from being received by ScribbleArea::keyPressEvent, which in turn broke the delete selection action. This PR reverts the creation of the new shortcut, and uses PolylineTool::keyPressEvent instead to trigger this behavior. This allows for both the polyline tool and selection to use the backspace shortcuts. I also think this is a better way to do things code-wise.
However, it does mean that the polyline delete segment action is another one of shortcuts which is currently hardcoded. I do think it was a nice idea to have this as a customizable shortcut, but I think window-level shortcuts were the wrong way to go about this, or at the very …
> Use keyPressEvent rather than shortcut for polyline delete segment

- .github/actions/create-package/create-package.sh
- .github/actions/install-dependencies/install-dependencies.sh
- .github/actions/setup-environment/setup-environment.sh
- .github/workflows/ci.yml
I found some time to get this working again. It’s slightly annoying to do because actions cannot be run in a container selectively, but this should do for now.
> Run actions outside container to fix Linux build failure

- ChangeLog.md
- app/src/actioncommands.cpp
- core_lib/src/graphics/bitmap/bitmapimage.cpp
- core_lib/src/interface/editor.cpp
- core_lib/src/managers/clipboardmanager.cpp
- core_lib/src/managers/clipboardmanager.h
- core_lib/src/structure/filemanager.cpp
- core_lib/src/structure/filemanager.h
Upon reviewing the code used to copy keyframes, multiple issues were found. These issues are:
A memory leak in ClipboardManager where cloned frames are not deleted. Normally KeyFrame deletion is handled by Layer, but since the KeyFrames held in the clipboard are not part of a layer, deleting them must be handled separately.
Suffixes are always added to BitmapImages. This works as expected when cloning regular images, however when cloned images are cloned, the resulting image's filename has two suffixes. Repeat this, adding 13 characters each time, and the filename can quickly exceed the maximum length of a filename on some systems. This issue exists for various methods for copying bitmap images, but it is most obvious with copy and pasted keyframes because they are cloned twice (once to …
> Fix some issues related to frame copying & change pcl working directory

- core_lib/src/managers/toolmanager.cpp
- core_lib/src/managers/toolmanager.h
- core_lib/src/tool/basetool.cpp
- core_lib/src/tool/basetool.h
- core_lib/src/tool/brushtool.cpp
- core_lib/src/tool/brushtool.h
- core_lib/src/tool/buckettool.cpp
- core_lib/src/tool/buckettool.h
- core_lib/src/tool/cameratool.cpp
- core_lib/src/tool/cameratool.h
- core_lib/src/tool/erasertool.cpp
- core_lib/src/tool/erasertool.h
- core_lib/src/tool/eyedroppertool.cpp
- core_lib/src/tool/eyedroppertool.h
- core_lib/src/tool/handtool.cpp
- core_lib/src/tool/handtool.h
- core_lib/src/tool/movetool.cpp
- core_lib/src/tool/movetool.h
- core_lib/src/tool/penciltool.cpp
- core_lib/src/tool/penciltool.h
- core_lib/src/tool/pentool.cpp
- core_lib/src/tool/pentool.h
- core_lib/src/tool/polylinetool.cpp
- core_lib/src/tool/polylinetool.h
- core_lib/src/tool/selecttool.cpp
- core_lib/src/tool/selecttool.h
- core_lib/src/tool/smudgetool.cpp
- core_lib/src/tool/smudgetool.h
- core_lib/src/tool/stroketool.cpp
- core_lib/src/tool/stroketool.h
Tool properties are written to disk immediately when changed. If you try to slide a scalar value with a high temporal resolution device like a tablet or a high end mouse, the flooding events will cause the program to freeze/lag as it struggles to write every value to the QSettings object.
Previously #1853 was merged to mitigate this problem with quick sizing, but if you change the properties on the tool options panel, the lag is still there.
This PR makes the change so that the program will wait until you switch to another tool, or close the program, to write everything onto the disk.
> Write tool properties to disk when calling leavingThisTool() or ~ToolManager()

- core_lib/src/interface/scribblearea.cpp
- core_lib/src/tool/movetool.cpp
Gives an option for the artist to transform without smoothing. Useful for pixel art.
> Enable antialiasing option for move tool

- LICENSE.TXT
Replaces the contents of LICENSE.txt with the latest https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
- FSF is now remote-only, so there is no longer a postal address
- References to the Library GPL are now to the Lesser GPL
- Some placeholders have been changed
- Some headings have been realigned with different whitespace
> Use the latest GPLv2 license text

- app/app.pro
- app/src/actioncommands.cpp
- app/src/actioncommands.h
- app/src/mainwindow2.cpp
- app/src/mainwindow2.h
- app/src/toolbox.cpp
- app/src/toolbox.h
- app/src/toolboxwidget.cpp
- app/src/toolboxwidget.h
- app/src/tooloptionwidget.cpp
- app/ui/toolboxwidget.ui
- core_lib/core_lib.pro
- core_lib/src/interface/flowlayout.cpp
- core_lib/src/interface/flowlayout.h
- core_lib/src/interface/toolboxlayout.cpp
- core_lib/src/interface/toolboxlayout.h
I've given our FlowLayout class an overhaul.
Pure row height calculation has been moved into its own separate function, rather than mixing everything with the "testOnly" flag. The justified logic has been updated such that it will always try to cram as many items on a line as possible, but still be constrained to a minimum spacing.
The result of that looks like this:
| Before | After |
| ------ | ----- |
| ![old-flowlayout](https://github.com/user-attachments/assets/44186692-5de6-428a-92e1-163cca4d6a49) | ![new-flowlayout](https://github.com/user-attachments/assets/7c36c4ec-55c9-4460-8d2a-8513e6539c37) |
The sizing logic for the Tools widget has been updated as well. If there's only one row, then the items will be aligned centered and otherwise the alignment will change to justified, …
> UI Feature: Improve toolbox flow layout

- app/src/timelinecells.cpp
- core_lib/src/managers/layermanager.cpp
- core_lib/src/structure/keyframe.cpp
- core_lib/src/structure/keyframe.h
- core_lib/src/structure/layer.cpp
- core_lib/src/structure/layer.h
- tests/src/test_layer.cpp
The reason for this is that while we keep a list of selected keyframes to move and paint on the timeline, a keyframe also has its own "isSelected" state. This state is backed up through undo/redo operations while the layer::getSelectedFrames is not.
We use the isSelected state to ignore selected frames in the TimeLineCells::paintFrames while we use Layer::getSelectedFrames() to paint the selected frames.
This means that we can get into a situation where the frame is neither painted as selected nor non selected because of the two different sources of truth.
The solution is to remove one of the sources. As such, I went ahead and removed isSelected from Keyframe, so there's only one truth. By doing so, said frames can no longer be put in a selected state through undo/redo operations, which I …
> Fix #1873 - Fix frame not being drawn on the timeline

- core_lib/src/tool/polylinetool.cpp
Small fix for a bug that was just reported on the forum. Apparently we've had it for some time...
It might not be as easy to backmerge as some other things because this uses the old backup system where as that's changed in master.
I still think we should include it though.
I also fixed a behaviour inconsistency between keyboard and mouse where as double-clicking would include the current point on end, doing the same with keyboard would not.
source: https://discuss.pencil2d.org/t/the-polyline-tool-acts-weird-when-trying-to-undo/9833/3
> Fix polyline not creating a backup on end with keyboard

- .github/actions/notarize-macos-app/action.yml
- .github/workflows/ci.yml
Hi all, this PR implements macOS code signing and notarization in the GitHub Action when creating the Pencil2D macOS app. 
Issue: #1922 
This ensures we meet Apple's security requirements and provide a better user experience, particularly to avoid the very annoying security warning.
This codesign & notarization process requires 6 GitHub actions secrets to work. I have added them to our repo.
If you don't have them, don't worry the notarization step will be skipped, and it will just work the same as before.
---
For anyone who wants to code-sign the app with your own Apple developer account, you need to
1. Go to Apple Developer website and request a "Developer ID Application" certificate
2. Download and install the certificate to your local Keychain Access
3. Open Keychain Access and export …
> #1922 Implement macOS codesign & notarization

- core_lib/src/util/util.cpp
- core_lib/src/util/util.h
- tests/src/test_layerbitmap.cpp
- tests/src/test_layersound.cpp
- tests/src/test_layervector.cpp
This PR creates a new function `closestCanonicalPath` that behaves like `QDir::canonicalPath`, except that it will try to resolve symlinks for the nearest existing directory in the path if the path passed as an argument does not exist. For example, if `/symlink` points to the directory `/target`, then `QDir("/symlink/example.txt").canonicalPath()` and `closestCanonicalPath("/symlink/example.txt")` will both return `/target/example.txt` if example.txt exists. If it does not exist, then `QDir::canonicalPath` will output an empty string while this new function will still output `/target/example.txt`.
The motivation for this new function is twofold. It can be used to greatly simplify the implementation of `validateDataPath`, which was much more complex that it would seem on first glance and I …
> Refactor validateDataPath and fix macOS unit tests

- .github/workflows/ci.yml
Because Qt6 is no longer available on macOS Ventura.
Since it's the Qt6 build, it should not matter much which image we're running on compatibility wise.
> Bump Qt6 macOS runner to Sonoma

- app/src/checkupdatesdialog.cpp
This is a really minimal solution to avoid release candidates from being presented as a new release when users check for updates. The releases.atom does not provide the information necessary to distinguish prereleases from full releases. The nightly build link was wrong so I updated that at the same time.
I would like to eventually use the GitHub API instead, which does provide prerelease information, and fall back to the atom, or perhaps even other sources in case GitHub is down or blocked. However I'm going to leave that as a future improvement as I want to get this fix into v0.7.1. Given how close v0.7.1 is to release, I think this small hack is the best short-term solution.
> Filter release candidates out of update checker
