pencil2d/pencil

- app/commandcenter.cpp
- app/displayoptionwidget.cpp
- app/mainwindow2.h
- app/ui/displayoption.ui
- core_lib/interface/editor.cpp
- core_lib/interface/editor.h
- core_lib/interface/scribblearea.cpp
- core_lib/interface/scribblearea.h
- core_lib/managers/layermanager.cpp
- core_lib/managers/layermanager.h
- core_lib/structure/layersound.h
- core_lib/util/pencildef.h
- core_lib/util/util.h
- tests/test_layermanager.cpp
- tests/test_layermanager.h
Never used pull requests before... but uh, yeah, the master branch of my fork is identical to the current pencil2d/pencil dev branch, except with the addition of a button to toggle camera visibility.
Am I supposed to make more changes before I create a pull request, or is this fine?
> Am I doing this right?

- app/preferencesdialog.cpp
- app/preferencesdialog.h
- app/ui/displayoption.ui
- app/ui/mainwindow2.ui
- app/ui/timeline2.ui
- core_lib/canvasrenderer.cpp
- core_lib/canvasrenderer.h
- core_lib/graphics/bitmap/bitmapimage.cpp
- core_lib/graphics/bitmap/bitmapimage.h
- core_lib/interface/scribblearea.cpp
- core_lib/interface/scribblearea.h
- core_lib/interface/tooloptiondockwidget.cpp
- core_lib/managers/preferencemanager.cpp
- core_lib/managers/preferencemanager.h
- core_lib/structure/layer.cpp
- core_lib/tool/brushtool.cpp
- core_lib/tool/brushtool.h
- core_lib/tool/erasertool.cpp
- core_lib/util/pencildef.h
- pencil.pro
I've fixed the (in my opinion) very distracting bug where a brush stroke overlaps itself, causing it to be darker than it should be. I also improved the accuracy of brush feathering (although it's not as smooth - might need some work in the future) and made a couple changes to the UI (nothing huge there, though). I also made it possible to disable the blur on zooming (in preferences)
> Brush alpha handling improved and a few changes to the UI design

- resources/translations/pencil2d_da.ts
- resources/translations/translations.pro
Pencil2D translated to danish, for those who want.
> Added Danish translation

- app/mainwindow2.cpp
Fixed my boo boo.  Happy new year.
> moved mEditor->setObject( object ) to correct position

- core_lib/structure/editorstate.h
> Have application start with black color selected even after New file

- app/mainwindow2.cpp
- core_lib/interface/editor.cpp
> Fix import image

- core_lib/interface/timeline.cpp
- core_lib/interface/timeline.h
This pull request allows you to scroll up and down in the timeline area with the mouse scroll wheel
If this was a problem for #337, then it is now resolved
> Add scrolling timeline via wheel

- core_lib/interface/editor.cpp
- core_lib/structure/editorstate.h
When creating a new document, bitmap layer should be selected by default
#374 #397 #409
> Start on bitmap layer

- core_lib/canvasrenderer.cpp
> Clear the selection area only on the frame that's selected

- app/app.pro
- app/mainwindow2.cpp
- app/mainwindow2.h
- app/shortcutfilter.cpp
- app/shortcutfilter.h
- core_lib/interface/scribblearea.cpp
- core_lib/interface/scribblearea.h
Fixes #353 
To have this compile correctly, you will need to regenerate the app Makefile by executing the following
rm app/Makefile
qmake
> Block shortcut keys if the mouse is active

- core_lib/graphics/vector/beziercurve.cpp
- core_lib/graphics/vector/beziercurve.h
- core_lib/interface/scribblearea.cpp
- core_lib/interface/tooloptiondockwidget.cpp
- core_lib/interface/tooloptiondockwidget.h
- core_lib/managers/toolmanager.cpp
- core_lib/managers/toolmanager.h
- core_lib/tool/basetool.cpp
- core_lib/tool/basetool.h
- core_lib/tool/polylinetool.cpp
- core_lib/util/pencildef.h
Fixes #309 
This branch adds a "Bezier" toggle to the poly tool allowing you to switch between straight lines and bezier curve fitting
> Polyline 309

- core_lib/interface/timelinecells.cpp
Should this have been put in on a branch other than the master?
> Fixes bug https://github.com/pencil2d/pencil/issues/424

- core_lib/canvasrenderer.cpp
- core_lib/interface/scribblearea.cpp
- core_lib/tool/handtool.cpp
- core_lib/tool/handtool.h
- core_lib/tool/selecttool.cpp
Fixed bug https://github.com/pencil2d/pencil/issues/446
Fixed bug https://github.com/pencil2d/pencil/issues/442
> Bug fixing

- app/mainwindow2.cpp
- app/mainwindow2.h
> Fix undo/redo

- core_lib/interface/timeline.cpp
- core_lib/interface/timelinecells.cpp
I had some weird things happening on my previous pull request on my bugFix branch.
I did a git cherry-pick  to move the two commits that address drag and drop as well as scrolling issues.
> Addresses drag and drop and  scrollbar detailed in issue #436

- core_lib/interface/scribblearea.cpp
> Fix #443,Polyline & Pen width confilct

- app/colorwheel.cpp
- app/colorwheel.h
See #426 for details on the issue being fixed by this.
> Stopped color wheel changes from resetting alpha

- core_lib/graphics/bitmap/bitmapimage.cpp
> Use Qimage null image to clean up bitmap

- core_lib/interface/scribblearea.cpp
- core_lib/managers/viewmanager.cpp
- core_lib/managers/viewmanager.h
I think this would be nice to have, but it's probably just my opinion. I'd like to have a discussion about this. :3
> Motified zooming when using mouse wheel.

- .github/ISSUE_TEMPLATE.md
Reorganized the titles and wrapped descriptions inside markdown-style comments.
> Update issue template based on submission feedback.

- app/main.cpp
- app/mainwindow2.cpp
- app/shortcutfilter.cpp
- app/shortcutfilter.h
- core_lib/interface/timecontrols.cpp
- core_lib/interface/timelinecells.cpp
- core_lib/interface/timelinecells.h
- core_lib/managers/toolmanager.cpp
- core_lib/tool/handtool.cpp
- core_lib/tool/handtool.h
- core_lib/tool/movetool.cpp
- core_lib/tool/movetool.h
- core_lib/tool/selecttool.cpp
- core_lib/tool/selecttool.h
> Fix a few memory leaks

- app/app.pro
- app/errordialog.cpp
- app/errordialog.h
- app/mainwindow2.cpp
- app/resource/app.qrc
- app/resource/icons/dialog-error.svg
- app/ui/errordialog.ui
- core_lib/core_lib.pro
- core_lib/graphics/vector/bezierarea.cpp
- core_lib/graphics/vector/bezierarea.h
- core_lib/graphics/vector/beziercurve.cpp
- core_lib/graphics/vector/beziercurve.h
- core_lib/graphics/vector/vectorimage.cpp
- core_lib/graphics/vector/vectorimage.h
- core_lib/structure/filemanager.cpp
- core_lib/structure/layer.cpp
- core_lib/structure/layer.h
- core_lib/structure/layerbitmap.cpp
- core_lib/structure/layerbitmap.h
- core_lib/structure/layercamera.cpp
- core_lib/structure/layercamera.h
- core_lib/structure/layersound.cpp
- core_lib/structure/layersound.h
- core_lib/structure/layervector.cpp
- core_lib/structure/layervector.h
- core_lib/util/pencilerror.cpp
- core_lib/util/pencilerror.h
- pencil.pro
This includes many changes made with the goal of improving the reporting of errors during file saving (like #520 Case A). List of significant changes:
- Created a new ErrorDialog class that can be used to display error messages with full details
- Expanded Status class (pencilerror.h) functionality to store titles and descriptions for displaying to the user, and a details section for holding variable states, messages, cpu information and anything else that developers would find useful for debugging the error.
- Made use of the new Status functionality wherever possible within the document saving code (esp. in vectorimage and filemanager).
- Use QXmlStreamWriter for VectorImage saving. The XML module is not being maintained anymore and the stream writer can be used for element-level error …
> Display detailed error dialog on save failure

- app/app.pro
- app/ui/errordialog.ui
- core_lib/core_lib.pro
- core_lib/structure/filemanager.cpp
- core_lib/structure/layerbitmap.cpp
- core_lib/structure/layervector.cpp
- pencil.pro
I had fixed all of these things before I made the last PR, but it seems I forgot to commit them.
> Bugfixes for error dialog

- core_lib/structure/object.cpp
- core_lib/structure/object.h
This is a fix for #545. The temporary working folder is now cleared to prevent this bug occurring.
> Fix for bug #545 (sticky frame)

- core_lib/canvasrenderer.cpp
> fix camera border taking up 1 pixel of the canvas

- app/app.pro
- app/imageseqdialog.cpp
- app/imageseqdialog.h
- app/mainwindow2.cpp
- app/mainwindow2.h
> Added dialog to adjust frame spacing for imported image sequence

- core_lib/structure/filemanager.cpp
I'm actually not sure what to do with the translations, that contains that typo.  will they be updated automatically from onesky?
> fix typo s,sufficent,sufficient,g

- .travis.yml
> missing cd command in travis script

- .travis.yml
Hopefully this fixes the OS X build. It's untested.
> remove makefile and fix for broken OSX build

- core_lib/managers/soundmanager.cpp
- core_lib/managers/soundmanager.h
I came across this by chance, looks like a typo to me.
> createMeidaPlayer → createMediaPlayer

- app/mainwindow2.h
another possibility is to do this via qmake, I did it here as it's just quicker to do.
> in the title use GIT_TIMESTAMP if defined, instead of __DATE__

- app/aboutdialog.cpp
- app/app.pro
After much trial and error, I finally figured a combination of quotes and backslashes that works on windows.
> Fix appveyor.

- core_lib/interface/timecontrols.cpp
- core_lib/interface/timecontrols.h
- core_lib/interface/timeline.cpp
I've fixed the gaps in the timeline UI and refactored a bit on the timeline UI code.
> a bit refactoring and fixed timeline UI spacing

- app/app.pro
- app/mainwindow2.cpp
- app/ui/mainwindow2.ui
- core_lib/interface/scribblearea.cpp
- core_lib/interface/scribblearea.h
- core_lib/tool/brushtool.cpp
- core_lib/tool/erasertool.cpp
- core_lib/tool/penciltool.cpp
- core_lib/tool/pentool.cpp
- core_lib/util/pencildef.h
- resources/kb.ini
Removed references to popup palette and fixed a regression that would prevent painting from being placed on top of grid until updated.
> removed unused code and fixed a regression bug.

- core_lib/tool/movetool.cpp
- core_lib/tool/movetool.h
Additionally I've also made it slightly easier to select a corner.
> Refactored move tool

- .travis.yml
> regression: re-added macdeployqt fix

- core_lib/graphics/vector/vectorimage.cpp
After I merged master, suddenly my builds started failing, so I went ahead and fixed it.
Probably a leftover from 83b19e24af43bae2721133531b58fe453e7d8c42
> Fix compilation

- app/mainwindow2.cpp
Signed-off-by: Mattia Rizzolo <mattia@debian.org>
> fix typo s/sucessfully/successfully/

- app/tooloptionwidget.cpp
- app/tooloptionwidget.h
from comment in #687 
Is that fine @chchwy or did you have something else in mind?
> ToolOption button visibility refactoring.

- .travis.yml
@CandyFace needs at least 5.3 for his new fill algorithm and the version on the ubuntu that Travis
has is older, so here’s an update to 5.9 LTS.
> Use Qt 5.9.1 on Travis

- appveyor.yml
I made a syntax mistake due to my unfamiliarity with winbatch and forgot to test it properly. Sorry for the noise!
> Fix forced nightly uploads on AppVeyor

- core_lib/interface/scribblearea.cpp
- core_lib/interface/scribblearea.h
- core_lib/tool/movetool.cpp
- core_lib/tool/movetool.h
Nice and proper selection flipping ╭( ･ㅂ･)و
> Proper x/y selection flip implemented

- core_lib/interface/scribblearea.cpp
> proper view transformation for vector layer (only cursor)

- appveyor.yml
- util/checkchanges-win.ps1
- util/checkchanges.sh
I've tested this a couple of times now, and it seems to work.
Unfortunately I had to make another script for windows too, as I couldn't get appveyor's internal skip_commit.files to work.
> fixed ignoring files

- app/actioncommands.cpp
- app/actioncommands.h
- app/exportmoviedialog.cpp
- app/exportmoviedialog.h
- app/ui/exportmovieoptions.ui
- core_lib/managers/layermanager.cpp
- core_lib/managers/layermanager.h
- core_lib/structure/layer.cpp
- core_lib/structure/layer.h
* Ability export movie with specified range.
* Made it possible to type higher resolution values.
* checkbox to quickly switch between whole project length or last painted keyframe.
> Ability export movie with specified range

- 3rdlib/quazip/quazip.pro
- 3rdlib/zlib/zlib.pro
- app/colorpalettewidget.cpp
- app/mainwindow2.cpp
- app/mainwindow2.h
- core_lib/managers/layermanager.h
- core_lib/soundplayer.cpp
- core_lib/structure/filemanager.cpp
- core_lib/structure/layersound.cpp
- core_lib/tool/buckettool.cpp
Clean up the warnings and make some changes to the modified animation warning.
> Minor fixes

- app/colorpalettewidget.cpp
- app/colorpalettewidget.h
This is a subset of #719. This adds support for inline name editing, tooltips in grid mode, and fixes a minor selection bug in the color palette (which I can't seem to replicate anymore), without adding the buggy color drag support.
> Color palette improvement subset

- core_lib/tool/brushtool.cpp
- core_lib/tool/penciltool.cpp
- core_lib/tool/pentool.cpp
I do not have a tablet available to test this on at the moment, but this *should* fix #797
> Fix full pressure dabs

- core_lib/tool/erasertool.cpp
- core_lib/tool/erasertool.h
Adds support for eraser dabs, and fixes the bug where the eraser strokes were always being feathered.
> Minor eraser improvements

- app/main.cpp
- core_lib/interface/editor.cpp
- core_lib/interface/editor.h
See https://github.com/pencil2d/pencil/pull/813#discussion_r153343844. New PR since #813 already got merged.
> Add options for CLI rendering

- .travis.yml
- app/aboutdialog.cpp
- app/mainwindow2.h
- appveyor.yml
Merge extra changes in the release branch into master and use conditional statements to change the build settings on the release branch instead of always having differing branches.  This should also be merged into the release branch eventually so they are the same. Theoretically my changes will not affect anything on either the master or release branches.
> Sync master with release

- app/colorbox.cpp
- app/colorinspector.cpp
- app/colorwheel.cpp
- app/colorwheel.h
#816 
Additionally I've also added a degree symbol to the hue spinbox.
> Fixed colorinspector spinboxes behaving unusually

- appveyor.yml
```
if %APPVEYOR_REPO_BRANCH%!=release call qmake ..\ -tp vc -r "%APPVEYOR_BUILD_FOLDER%\pencil.pro" CONFIG+=GIT CONFIG+=NIGHTLY
=release was unexpected at this time.
Command exited with code 255
```
Tested and works now.
> use correct NOT conditional operator

- core_lib/managers/playbackmanager.cpp
- core_lib/structure/layer.h
feature request: #747 
Disabling a layer will now turn off the sound playing on that layer.
> enhancement: don't play sound when layer is hidden.

- app/toolbox.cpp
- app/toolbox.h
> fixed resize bug when layout was either one row or column

- util/Doxyfile-Travis
See https://github.com/pencil2d/pencil/pull/893#issuecomment-365741177
> Add Qt tag files to Doxyfile-Travis as well

- .travis.yml
> Include Qt SVG plugin in AppImages

- app/src/colorinspector.cpp
- app/src/colorinspector.h
- app/src/colorpalettewidget.cpp
In my hurry trying to push this out the door before going to work... I missed some remains of my savedColor
It should also be mentioned that when I said 
> Remember color values from last session
I meant when opening a project, the color from last time you had Pencil open won't be saved.
> remove savedColor remains

- app/src/colorinspector.cpp
- app/src/mainwindow2.cpp
Looks like I forgot this when I stashed some things.
> only show style if docked

- core_lib/src/tool/movetool.cpp
- core_lib/src/tool/movetool.h
- core_lib/src/tool/selecttool.cpp
This should fix #974, #973 and add the commit that @martinvanzijl made a PR for #881 (but was withdrawn again) some time ago
> Selection move fixes

- app/src/aboutdialog.cpp
- app/src/mainwindow2.cpp
- app/src/mainwindow2.h
- app/ui/errordialog.ui
- core_lib/src/structure/filemanager.cpp
- core_lib/src/util/pencildef.h
- core_lib/src/util/pencilerror.cpp
> Improve error dialog when open file fails

- app/src/actioncommands.cpp
- app/src/exportimagedialog.cpp
- app/src/exportimagedialog.h
- app/ui/exportimageoptions.ui
As per request #951 you can now export an image sequence with a given range.
> Add range to export image sequence

- core_lib/src/interface/editor.cpp
- core_lib/src/structure/layercamera.cpp
- core_lib/src/structure/layercamera.h
- core_lib/src/structure/object.cpp
- core_lib/src/structure/object.h
> Update view when camera resolution changes

- core_lib/src/interface/editor.cpp
- core_lib/src/interface/editor.h
- core_lib/src/movieexporter.cpp
- core_lib/src/structure/object.cpp
- core_lib/src/structure/object.h
Fix #1002 
1321 frame project, 1 bitmap layer.
Before
After
> Fix #1002 the high memory usage when exporting a long project to a movie

- core_lib/src/movieexporter.cpp
This gets rid of all that ugly custom code for handling wavs, fixes issues when the audio starts outside of the export range, probably improves audio syncing, and is way faster.
Fixes #1000.
> Refactor assembleAudio to use ffmpeg

- app/src/actioncommands.cpp
- app/src/actioncommands.h
- core_lib/src/interface/timelinecells.cpp
A function added that suggest new filenames, that differ from existing ones.
If you want a new "Bitmap Layer" and a "Bitmap Layer" exists, it will suggest "Bitmap Layer 2" as filename, and so on.
> Filename suggestion (numbers) for new layers in Pencil2D

- app/src/mainwindow2.cpp
- app/ui/mainwindow2.ui
Too bad I first discovered this bug now, but better now than after the release.
> Error counting digits fixed

- core_lib/src/movieexporter.cpp
Fixes the issue with sounds starting off quiet and progressively getting louder. There's a small possibility it will fix the no-sound issue too.
Fixes #1138
> Fix audio volume in movie export

- core_lib/src/interface/scribblearea.cpp
- core_lib/src/tool/brushtool.cpp
Fixed not being able to undo brush stroke
Fixed Canvas cursor not updating unless button was pressed.
> Fix canvas bugs

- app/src/main.cpp
- core_lib/src/structure/filemanager.cpp
This has been tested on Ubuntu together with @davidlamhauge
> Fixes #940 - force dot separator on numbers

- ChangeLog.md
- Added section descriptions for features, enhancements and fixes
> Updated 0.6.3 Change Log

- app/src/colorpalettewidget.cpp
- app/src/colorwheel.cpp
- app/src/colorwheel.h
- app/src/mainwindow2.cpp
- app/src/tooloptionwidget.cpp
- app/ui/mainwindow2.ui
- app/ui/shortcutspage.ui
- app/ui/tooloptions.ui
- core_lib/src/canvaspainter.cpp
- core_lib/src/graphics/bitmap/bitmapimage.cpp
- core_lib/src/interface/editor.cpp
- core_lib/src/interface/editor.h
- core_lib/src/interface/scribblearea.cpp
- core_lib/src/managers/playbackmanager.cpp
- core_lib/src/managers/toolmanager.cpp
- core_lib/src/structure/layerbitmap.cpp
- core_lib/src/tool/basetool.cpp
- core_lib/src/tool/movetool.cpp
- core_lib/src/util/pencildef.h
Here are a bunch of small bugfixes, mostly to unreported issues that I took note of during my personal testing last month of v0.6.3. Just read the commit messages to see what's been fixed in this PR. 
A friendly reminder that the deadline for our first bug fix release is about a week away. 5aa4d9c and b293c28 are the most important fixes here and are probably worth making the bugfix release for them alone. There are still *a lot* of bugs though, if any of you developers feel up to it :wink:. There is at least one other bug I need to fix before v0.6.4, and a few others I would like to see fixed, so there will probably be another PR after this. Let's try and get one release out on time! 😁
> Batch 1 of bug fixes

- core_lib/src/activeframepool.cpp
- core_lib/src/canvaspainter.cpp
- core_lib/src/graphics/bitmap/bitmapimage.cpp
- core_lib/src/interface/backgroundwidget.h
- core_lib/src/interface/flowlayout.cpp
- core_lib/src/interface/flowlayout.h
- core_lib/src/interface/recentfilemenu.h
- core_lib/src/interface/scribblearea.cpp
- core_lib/src/interface/scribblearea.h
- core_lib/src/interface/timecontrols.h
- core_lib/src/interface/timeline.cpp
- core_lib/src/managers/basemanager.h
- core_lib/src/managers/colormanager.h
- core_lib/src/managers/layermanager.h
- core_lib/src/managers/preferencemanager.h
- core_lib/src/managers/soundmanager.cpp
- core_lib/src/managers/soundmanager.h
- core_lib/src/managers/toolmanager.cpp
- core_lib/src/managers/viewmanager.cpp
- core_lib/src/movieexporter.cpp
I have the vision, that someday we can build Pencil2D without warnings of any kind.
This PR resolves about 60 warnings. It's mainly 0 or NULL that's changed to nullptr, and old C casts changed to C++ casts.
> Warnings resolved

- app/src/mainwindow2.cpp
- core_lib/src/graphics/bitmap/bitmapimage.cpp
- core_lib/src/graphics/bitmap/bitmapimage.h
- core_lib/src/interface/scribblearea.cpp
Here is a series of small enhancements (or bug fixes that need to be done on master). The commit messages should be fairly self-explanatory.
Special thanks to @CandyFace for bringing to my attention some ways of improving the flood fill speed.
> Miscellaneous enhancements

- app/src/tooloptionwidget.cpp
- core_lib/src/tool/brushtool.cpp
- core_lib/src/tool/brushtool.h
> Remove brush toggle buttons for AA and feathering

- app/src/filedialogex.cpp
> iss1330 - fix suffix being added even though one exists

- core_lib/src/interface/timeline.cpp
Vertical Scrollbar didn't update properly, since layer count didn't update properly.
Closes #1338
> 1338 Vertical scrollbar updates properly

- .travis.yml
- app/src/main.cpp
- core_lib/src/external/linux/linux.cpp
- core_lib/src/external/macosx/macosx.cpp
- core_lib/src/external/platformhandler.h
- core_lib/src/external/win32/win32.cpp
- util/after-build.sh
This is a followup to #1341 with the changes that I have recommended. The biggest changes are the refactoring of some of the code in main to PlatformHandler and adding the apetag gstreamer plugin. Hopefully this will fix the issue with some mp3s not playing :crossed_fingers:
> Appimage sound followup

- app/app.pro
This is an extremely trivial change, but I would nonetheless like a quick review of the macOS-specific part because I’m not an Apple user.
> Add install support for other Unixes

- tests/src/test_filemanager.cpp
just added a new test to the end of the test_filemanager file.
> added invalid sound frame test

- tests/src/test_colormanager.cpp
- tests/tests.pro
added test_colormanager.cpp and updated tests.pro to include the new test file
> added test_colormanager.cpp

- app/src/preferencesdialog.cpp
Fixed a typo in preferencesdialog.cpp
Maybe it's easier to edit it in the code directly, if someone's up to it.
> Fixed typo in preferencesdialog.cpp

- core_lib/src/canvaspainter.cpp
> #1433 - Fix polyline painting issue for vector

- core_lib/src/tool/polylinetool.cpp
> #1435 - Fix polyline buffer not being cleared.

- README.md
Updated the readme.md file to include links and info relevant to a new-user, or in other words someone who is visiting the github page for the first time.
> Improved new-user experience

- core_lib/src/managers/layermanager.cpp
This fixes a bug where, when deleting the last layer, the layer deletion was performed before actually switching away from the layer so that, for a brief moment, the current layer didn’t actually exist. This issue must have been around for a while, but it was recently exposed through the addition of the onCurrentLayerWillChange signal in #1724. Unfortunately I missed that while reviewing the PR, so on current master this bug means that deleting the last layer while it is active will actually result in a bunch of assertions to fire before the program ultimately crashes.
> Switch away from last layer before deleting it

- core_lib/src/interface/scribblearea.cpp
- core_lib/src/tool/basetool.h
- core_lib/src/tool/stroketool.cpp
- core_lib/src/tool/stroketool.h
As reported at https://discuss.pencil2d.org/t/pencil2d-crashes-when-trying-to-drawing-to-a-hidden-layer/8038?u=j5lx
> Fix crash when drawing on hidden layer

- core_lib/src/tool/polylinetool.cpp
> Fixed being unable to undo Polylines applied with Enter key
